### ISSUE TITLE
Cannot load .npy file saved by Numpy

### ISSUE THREAD

**Issue by TangToy** [dpilger26/NumCpp#102]
I saved an array using Numpy:
```
pred_np = pred.long().cpu().numpy()
np.save('pred_np.npy', pred_np)
```
And I want to load this array by Numcpp in C++:
```
nc::NdArray<long> label_hxyz = nc::load <long>("pred_np.npy");
```
I found using this code cannot load a correct array. What is the problem? Does this mean the .npy cannot be loaded in Numcpp?

**Comment by dpilger26** [comment]
No `NumCpp` does not support `.npy` or `.npz` file loading.  You can write out to a simple flat binary file from `NumPy`:

```python
pred_np.tofile('pred_np.bin')
```

and then read that back in with `NumCpp`

```cpp
auto label_hxyz = nc::load<long>("pred_np.bin");
```

**Comment by TangToy** [comment]
Thanks. I have tested your code. I found that after loading the .bin file, the dimension of the loaded array has been changed, so the  _reshape()_ is needed. The complete code are shown as follows:

Numpy:
```
pred_np.tofile('pred_np.bin')
```
Numcpp:
```
auto label_hxyz = nc::load<long>("pred_np.bin");
label_hxyz.reshape({10, 10});
```

**Comment by dpilger26** [comment]
That's correct. There is no information in the binary file about the shape of the original array so the read function will read into a flat 1 dimensional array.
