### ISSUE TITLE
How to realize element-wise slice in Numcpp?

### ISSUE THREAD

**Issue by TangToy** [dpilger26/NumCpp#103]
In Numpy, I can slice the array like this:
```
  test_np = np.array([1, 2, 3, 4, 5])
  indice = [2, 4]
  slice_np = test_np[indice]#[3, 5]
```
However, I have not found any API that can slice the array in Numcpp like this. It seems either _Slice()_ or _at()_ can not slice the array like this. Does it exist any API in Numcpp that can slice like this? Thanks!

**Comment by dpilger26** [comment]
You can slice with other `NdArray`s, for example:

```cpp
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>


int main ()
{
    nc::NdArray<int> testNcp = {1, 2, 3, 4, 5};
    nc::NdArray<nc::uint32> indices = {2, 4};
    auto sliceNcp = testNcp[indices]; // [3, 5]

    std::cout << sliceNcp;

    return EXIT_SUCCESS;
}
```

which outputs:

```bash
[[3, 5, ]]
```

**Comment by TangToy** [comment]
> You can slice with other `NdArray`s, for example:
> 
> ```c++
> #include "NumCpp.hpp"
> 
> #include <cstdlib>
> #include <iostream>
> 
> 
> int main ()
> {
>     nc::NdArray<int> testNcp = {1, 2, 3, 4, 5};
>     nc::NdArray<nc::uint32> indices = {2, 4};
>     auto sliceNcp = testNcp[indices]; // [3, 5]
> 
>     std::cout << sliceNcp;
> 
>     return EXIT_SUCCESS;
> }
> ```
> 
> which outputs:
> 
> ```shell
> [[3, 5, ]]
> ```

Thanks a lot. If I want to slice a 2-D array, like:
```
nc::NdArray<int> testNcp = { {1, 2}, {3, 4}, {5, 6},{7, 8} };
``` 
I want to get 
```
{ {3, 4}, {5, 6} };
```
How to slice _testNcp_ ？Thanks。

**Comment by dpilger26** [comment]
The easiest way would be:

```cpp
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>

int main ()
{
    nc::NdArray<int> testNcp = { {1, 2}, {3, 4}, {5, 6},{7, 8} };
    auto sliceNcp = testNcp({1, 3}, testNcp.cSlice());

    std::cout << sliceNcp;

    return EXIT_SUCCESS;
}
```

**Comment by TangToy** [comment]
Special thanks to you. Sorry for disturbing you again, I still have a question. I found `auto sliceNcp = testNcp({1, 3}, testNcp.cSlice());` can only slice continuous elements. If I define another testNcp:
```
 nc::NdArray<int> testNcp = { {1, 2}, {3, 4}, {5, 6},{7, 8}, {9, 10},{11, 12},{13,14} };
```
And I want to get:
```
{ {3, 4}, {5, 6} }, {9, 10}};//slice out several discrete elements, 
```
Like in Numpy:
```
testNcp = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14]])
slice_list = [1, 2, 4]
sliceNcp = testNcp[slice_list, :]#[[ 3  4]
                                   [ 5  6]
                                   [ 9 10]]

```
How to get sliceNcp in Numcpp like in Numpy? Thank you again.

**Comment by dpilger26** [comment]
That looks like an oversight by me as there is not currently a way to slice 2D arrays this way.  I've added it to my to-do list to add some more overloads for slicing in the next release.  Please keep this issue open for tracking those updates.

**Comment by TangToy** [comment]
Thanks.

**Comment by dpilger26** [comment]
Added additional slicing overloads to Release Version 2.5.0.

**Comment by reverse-2020** [comment]
> 

hi , i am new here, how does the additional slicing work? for example
import numpy as np

`a = np.random.randint(0, 100, (10,10))
print(a)

b = a[:, [1,4,5,7]] # just choose the col 1,4,5,7
or 
c = a[[2,8],:] #  just choose the row 2,8 `

thanks ,wish u happy new year!
