### ISSUE TITLE
How to assign values like b[2, :] = a[1,:] in Numpy

### ISSUE THREAD

**Issue by TangToy** [dpilger26/NumCpp#104]
I want to assign values like this in Numpy:
```
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
b = np.zeros([3, 2])
b[2, :] = a[1,:]
```
I tried to assign value in Numcpp like this:
```
nc::NdArray <float> _a = { {1,2},{3,4},{5,6} };
nc::NdArray <float> b = nc::zeros<float>(3, 2);
b(2, b.cSlice()) = _a(1, _a.cSlice());
std::cout << "b: " << b;
```
However, the output b is still zero arrays like:
```
b: [[0, 0, ]
[0, 0, ]
[0, 0, ]]
```
How to assign values? Thanks.

**Comment by dpilger26** [comment]
Remember that there is a key difference between `NumCpp` and `NumPy` in that `NumCpp` slices return new array copies, NOT references like `NumPy` does.  So in your example you are creating and setting the values of a temporary array that then gets thrown away in the next line.  For that reason you need to use the `NdArray` `put()` methods:

```cpp
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>

int main ()
{
    nc::NdArray<float> a = { {1, 2}, {3, 4}, {5, 6},{7, 8} };
    auto b = nc::zeros<float>({3, 2});

    b.put(2, b.cSlice(), a(1, a.cSlice()));

    std::cout << "b: " << b;

    return EXIT_SUCCESS;
}
```

which outputs:

```bash
b: [[0, 0, ]
[0, 0, ]
[3, 4, ]]
```

**Comment by TangToy** [comment]
Thanks a lot!
