### ISSUE TITLE
about multidimensional matrix

### ISSUE THREAD

**Issue by nanmi** [dpilger26/NumCpp#108]
**Describe the bug**
Can I implement multidimensional matrix in this way？
```cxx
nc::NdArray<nc::NdArray<int>> aa;// = {{{1,2,3},{4,5,6}},{{7,8,9},{10,11,12}}};
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dpilger26** [comment]
No this is not possible.
