### ISSUE TITLE
Latest boost version issue

### ISSUE THREAD

**Issue by varshapratapchavan** [dpilger26/NumCpp#109]
In my application, I want to display run time graphs. But the graphs can have a break in between i.e. data may not be available for some duration. I want to display this gap in my graph.

I want to use MATPLOTLIB library in my application which will run under Qt.

I am trying to use NUMCPP to create an array with breaks ( gaps) in my graph readings

While including NUMCPP, it prompts for - older BOOST version detected. Required version 1.68

I tried to upgrade to latest Boost version 1.68, but the link for downloading is not available.

Please suggest how to download the required version & include NUMCPP

Kindly suggest an option / solution

Regards

Varsha

**Comment by dpilger26** [comment]
Older versions of boost can be downloaded [here](https://boostorg.jfrog.io/ui/native/main/release/).  You can also define the compiler macro `NUMCPP_NO_USE_BOOST` in your project to disable any `NumCpp` features that require boost so that `NumCpp` will be completely standalone.
