### ISSUE TITLE
No match with parameter list

### ISSUE THREAD

**Issue by IMHinnG** [dpilger26/NumCpp#110]
When i use zeros_like with torch::Tensor data type (nc::zeros_like<torch::Tensor>(image)) and will show No match with parameter list.
Have any good solutions?thanks

**Comment by dpilger26** [comment]
That's correct.  `nc::zeros_like` takes in another `nc::NdArray` as its input.  The `NumCpp` library has no knowledge of other libraries such as `PyTorch` and was not designed to be compatible with them.  For this you'll have to get the dimensions from your `torch::Tensor` and pass them into `NumCpp`s `zeros()` method.

**Comment by PhoenixDai** [comment]
Is there a plan to support higher dimension tensors like what we can do with numpy: np.random.normal(0,1,(2,3,4,5))?

**Comment by dpilger26** [comment]
@PhoenixDai Yes there is a plan to support higher dimension arrays in Version 3.0.  I've even started working on it.  However, it is going to be awhile as I have a new born baby at home that is taking much of my free time now-a-days.

**Comment by PhoenixDai** [comment]
> @PhoenixDai Yes there is a plan to support higher dimension arrays in Version 3.0. I've even started working on it. However, it is going to be awhile as I have a new born baby at home that is taking much of my free time now-a-days.

Congratulations! Hope everyone is staying safe and healthy! Thanks a lot for the updates and I'm looking forward to these new features. My project has some performance bottleneck with Python now. I'm hoping NumCpp can help us meet the performance requirement but we use high dimensional tensors heavily. The NumCpp is the most easy-to-use and close to the Numpy API I've ever found so far. Please keep up this work and I believe the community appreciates it as well!
