### ISSUE TITLE
links to target "Boost::headers" but the target   was not found

### ISSUE THREAD

**Issue by ppdouble** [dpilger26/NumCpp#111]
boost 1.77 was extract from source package at `/usr/local/boost_1_77_0`.

Use `CmakeLists.txt` file below to build sample code at [https://github.com/dpilger26/NumCpp/blob/master/docs/markdown/Building.md#1-source-file](https://github.com/dpilger26/NumCpp/blob/master/docs/markdown/Building.md#1-source-file)

```
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>

int main()
{
    auto a = nc::random::randInt<int>({10, 10}, 0, 100);
    std::cout << a;

    return EXIT_SUCCESS;
}

```

```
cmake_minimum_required(VERSION 3.14) 
project("numcpp-example-prj" CXX)

set (BOOST_ROOT "/usr/local/boost_1_77_0")
add_executable(${PROJECT_NAME} numcpp-example.cpp)

find_package(NumCpp 2.1.0 REQUIRED)

target_link_libraries(${PROJECT_NAME}
    NumCpp::NumCpp
)
```

When run `cmake ..` in `build` folder, the boost is detected. But it seems not found `Boost::headers`.

```
...
-- Boost version: 1.77.0
-- Found NumCpp: /usr/local/include (found version 2.5.1)
-- Configuring done
CMake Error at CMakeLists.txt:5 (add_executable):
  Target "numcpp-example-prj" links to target "Boost::headers" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

**Comment by dpilger26** [comment]
I don't think you can set the `BOOST_ROOT` variable from within your `Cmakelists.txt` file like you are doing.  Try passing it into cmake at invocation time:

```bash
cmake -DBOOST_ROOT=/usr/local/boost_1_77_0 ..
```
