### ISSUE TITLE
can't support csv?

### ISSUE THREAD

**Issue by cqwuxiaolong** [dpilger26/NumCpp#113]
can't support csv?

**Comment by dpilger26** [comment]
Added some more delimiter support to the `fromfile` function in Release Version 2.6.1.  See the documentation [here](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#aa344c64ebbe94231d377f99775606c68)

```cpp
auto data = nc::fromfile<int>("myFile.csv", ',');
```
