### ISSUE TITLE
NdArrayCore.hpp master

### ISSUE THREAD

**Issue by moe123** [dpilger26/NumCpp#119]
**memory and performance killer**

- In argsort Axis::ROW/COL you are acquiring a new vector of indexes at each iteration; please move it out of the loop construct.
- It would be wise to think about writing a simple stable_sort column-wise instead of transposing in Axis::ROW.

-- Cheers!

**Comment by dpilger26** [comment]
Item 1 was fixed in Release Version 2.7.0.  Due to the cache unfriendliness of column wise operations it is unlikely that item 2 would result in any performance gains.

**Comment by moe123** [comment]
item 2 ; is a broad cowboy junkie statement; not really.
