### ISSUE TITLE
Ndarray subviews support.

### ISSUE THREAD

**Issue by luisluan** [dpilger26/NumCpp#12]
in matlab using one int vector's data as selector of another vector or matirx is supported. For example,
a=[9 8 7 6 5];
b=[5 1 3];
a(b) 
will give answer  [5 9 7]
using pointer in c++ together with Numcpp could fullfill this problem but seemed cumbersome.  so would you please add support for this functionality? like:
Ndarray<int> a= {9,8,7,6,5};
Ndarray<int> b={4,0,2,0};
a.select(b) represent {5,9,7,9}
by the way, it would be nice to add find, findfirst  findall methods which would return an Ndarray and could be used as selector of another Ndarray if it is int type.
thanks.

**Comment by dpilger26** [comment]
NumPy doesn't have a find method.  The way NumPy and NumCpp handle this scenario would be
 
    indices = np.nonzero(a < 7)

for example.  However I went ahead and added a convenience function to mimic Matlab.  Please see the documentation [here](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#a8eaa82071f16b2654f11096247ba10e5). 

As far as using one int array to index into another, this is already supported by NumCpp.  Here is a small code snippet demonstrating your question:

    #include "NumCpp.hpp"
    #include <iostream>
    
    using namespace nc;

    int main()
    {
        NdArray<int> a = { 9, 8, 7, 6, 5 };
        NdArray<int> b = { 4, 0, 2, 0};

        // use b as indices into a
        auto c = a[b.astype<uint32>()];  // requires indices to be of type uint32
        // or
        auto d = a.getByIndices(b.astype<uint32>());  // requires indices to be of type uint32
    
        std::cout << "c = \n" << c; // [[5, 9, 7, 9]]
        std::cout << "d = \n" << d; // [[5, 9, 7, 9]]
        std::cout << "array_equal(c, d) = " << std::boolalpha << array_equal(c, d) << std::endl;

        // using new find() function
        auto indices = find(a < 8);
        std::cout << "indices = \n" << indices; // [[2, 3, 4]]
        std::cout << "values = \n" << a[indices]; // [[7, 6, 5]]

        // find() has a second optional input for first number of indices to find
        auto firstIndex = find(a < 8, 1);
        std::cout << "firstIndex = \n" <<  firstIndex; // [[2]]
        std::cout << "value = \n" <<  a[firstIndex]; // [[7]]

        // find the first two indices
        auto firstTwoIndices = find(a < 8, 2);
        std::cout << "firstTwoIndices = \n" << firstTwoIndices; // [[2, 3]]
        std::cout << "value = \n" <<  a[firstTwoIndices]; // [[7, 6]]

        // Of course, values can also be found by directly masking in NumPy or NumCpp
        auto values = a[a < 8];
        std::cout << "values = \n" <<  values; // [[7, 6, 5]]

        return 0;
    }

**Comment by luisluan** [comment]
thanks.
