### ISSUE TITLE
nc::fmod does not accept <double> or NdArray<double>

### ISSUE THREAD

**Issue by keremcc** [dpilger26/NumCpp#121]
Hi Guys,

I would like to use python like % in cpp with NdArrays. I thought nc::fmod(NdArray double ,NdArray double ) is good candidate for this.

But although nc::remainder() method has same template structure with nc::fmod(),

nc::remainder() accepts  double or nc::NdArray double , 
nc::fmod does not accept double or nc::NdArray double.
Is this a bug, or I am missing something ?

Thanks

**Comment by dpilger26** [comment]
Changed in Release Version 2.7.0.
