### ISSUE TITLE
rSlice() does not give correct result when size.cols > size.rows

### ISSUE THREAD

**Issue by keremcc** [dpilger26/NumCpp#122]
Hi Guys,

rSlice() does not give correct result when size.cols > size.rows. I attached results below.

When **size.cols < size.rows**, it gives correct result. But if **size.cols > size.rows**, it slices column array until the max row value.

![Screenshot from 2021-12-01 11-40-46](https://user-images.githubusercontent.com/47608531/144275691-183230fd-7bf9-43be-b9be-bbe10d8252a7.png)

![Screenshot from 2021-12-01 11-29-28](https://user-images.githubusercontent.com/47608531/144274109-c654fd50-a5be-4c8e-ac3f-08be3968ba95.png)

In the above image, the expected result of Shape (0,:) should be **[1,4]**

**Comment by dpilger26** [comment]
You need to use `cSlice()` when slicing an entire column.

**Comment by keremcc** [comment]
My bad , I just realized rslice and cslice. Thank you.
