### ISSUE TITLE
fatal error: 'NumCpp/Coordinates/Coordinate.hpp' file not found

### ISSUE THREAD

**Issue by wingdi** [dpilger26/NumCpp#124]
I have add this in  CMakelists.txt:
`include_directories(NumCpp NumCpp/Coordinates)`
Why can't find it ?

**Comment by dpilger26** [comment]
You probably haven't included the directory correctly.  You should be using `target_include_directories` in place of `include_directories` now-a-days.  You've put in the path `NumCpp/Coordinates` as a relative path to your build directory and probably have it incorrect.  For example if your project was setup like this:

```bash
MyProject/
├── CMakeLists.txt
├── NumCpp
│   └── Coordinates
├── build
└── mySource.cpp
```

then your `CMakeLists.txt` would look like: 

```cmake
project(MyProject CXX)
add_executable(${PROJECT_NAME} mySource.cpp)
target_include_directories(${PROJECT_NAME}, ${CMAKE_CURRENT_BUILD_DIR}/../NumCpp/Coordinates)
```

To build you would:

```bash
>> cd build
>> cmake ..
>> cmake --build . --target MyProject
```

**Comment by wingdi** [comment]
Very thanks for your reply .

Here is a test Project:

This is CMakeLists.txt : 

<img width="1085" alt="截屏2021-12-05 下午1 01 02" src="https://user-images.githubusercontent.com/25787391/144734390-b7e14f4b-6615-41a3-8d85-652ecb1ce648.png">

This is mySource.cpp：

<img width="711" alt="截屏2021-12-05 下午1 01 14" src="https://user-images.githubusercontent.com/25787391/144734397-093339e3-e291-4214-83f8-0f6a03976c8e.png">

This is NumCpp folder copied from  NumCpp-master/include :

<img width="1268" alt="截屏2021-12-05 下午1 01 51" src="https://user-images.githubusercontent.com/25787391/144734401-3c589836-7799-4d28-8ac5-0c636a2d7176.png">

Developing tool is CLion.

It still get this error . even use file(glob .. ) , still didn't solve it.

**Comment by dpilger26** [comment]
I guess I don't understand why you are including the `NumCpp/Coordinates` directory if you aren't specifically including any of the files from that directory?  In your example above you are including the top level `NumCpp.hpp` header so will you need to include the directory that that file is in. eg.

```cmake
target_include_directories({$PROJECT_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_dir})
```

**Comment by wingdi** [comment]
Actually i want to include all the NumCpp, because the report error is about  _NumCpp/Coordinates_ , so i start solve from it..  
Now problem solved, thanks very much !
