### ISSUE TITLE
How can i initialization a  nc::NdArray<nc::NdArray<int>>  arr1 ? 

### ISSUE THREAD

**Issue by wingdi** [dpilger26/NumCpp#125]
Like c++ vector ：
`  std::vector<std::vector<std::vector<int>>>  arr2(5, std::vector<std::vector<int>>(10, std::vector<int>(3)));
` 
My data structure is 3D array,  nc::NdArray<int> arr seems like can't satisfied my need.

**Comment by dpilger26** [comment]
No this is not possible. Per the documentation and the `README`:

"The main data structure in `NumCpp` is the `NdArray`. It is inherently a 2D array class, with 1D arrays being implemented as 1xN arrays. There is also a `DataCube` class that is provided as a convenience container for storing an array of 2D `NdArray`s, but it has limited usefulness past a simple container."

**Comment by wingdi** [comment]
Ok, thanks . I will use 2D data.
