### ISSUE TITLE
np.linalg.norm(a)  --> nc::linalg::  ?

### ISSUE THREAD

**Issue by wingdi** [dpilger26/NumCpp#126]
Hi ,
I didn't find  linalg::norm(a),  is it in somewhere?

**Comment by dpilger26** [comment]
It isn't in the `linalg` namespace but you can find it in the top level `nc' namespace.  See the documentation [here](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#aa57b910a1d9a448a15e76bd72563ac5d).  For future reference, the documentation is searchable with the search box in the top right corner.

**Comment by wingdi** [comment]
Yes , it is, thanks .  
Before I thought it's  normalize or something , clearly i was wrong.
