### ISSUE TITLE
Conversion from cv::Mat CV_16UC1 to NdArray for uint16 type

### ISSUE THREAD

**Issue by keremcc** [dpilger26/NumCpp#127]
Hi Guys,

I am able to convert cv::Mat data to NdArray (nc::uint8) .
But I cant convert cv::Mat CV_16UC1 data to NdArray (nc::uint16). It gives error during build.
I guess library does not support uint16 conversion ?

Thanks in advance.
![Screenshot from 2021-12-21 17-50-34](https://user-images.githubusercontent.com/47608531/147007851-efff3035-08a7-457e-9367-dd313bba1022.png)
![Screenshot from 2021-12-21 17-50-58](https://user-images.githubusercontent.com/47608531/147007870-80d01c19-fbfc-4dbb-ae7a-1f858a0237bb.png)

**Comment by dpilger26** [comment]
It looks like the `cv::Mat::data()` method returns a pointer to `unsigned char` rather than `uint16_t`. Try `reinterpret_cast` on the pointer, eg:

```
auto NcArray = nc::NdArray<uint16_t>(reinterpret_cast<uint16_t*>(mymat.data), mymat.rows, mymat.cols);
```

**Comment by keremcc** [comment]
Thank you so much for quick reply. 
reinterpret_cast<uint16_t*>(mymat.data) worked for me. (Note: .ptr() didnt work)
