### ISSUE TITLE
vs2017 report error LNK 2005

### ISSUE THREAD

**Issue by luisluan** [dpilger26/NumCpp#13]
I got a vs2017 C++ project,which contains two source files and one header file as below:
exutil.h
`#pragma once`
`#ifndef EXUTIL_H`
`#define EXUTIL_H`
`#include "NumCpp.hpp"`
`#endif // !EXUTIL_H`

exutil.cpp
`#include "exutil.h"`

ex1.cpp
`#include "exutil.h"`

`int main()`
`{`
   `return 0; `
`}`

When building,  vs prompted:
exutil.obj : error LNK2005: "class boost::random::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253> nc::generator_" (?generator_@nc@@3V?$mersenne_twister_engine@I$0CA@$0CHA@$0BIN@$0BP@$0JJAILANP@$0L@$0PPPPPPPP@$06$0JNCMFGIA@$0P@$0OPMGAAAA@$0BC@$0GMAHIJGF@@random@boost@@A)  already defined in ex1.obj 

ex1.obj : error LNK2005: "class nc::NdArray<bool> __cdecl nc::imageProcessing::windowExceedances(class nc::NdArray<bool> const &,unsigned char)" (?windowExceedances@imageProcessing@nc@@YA?AV?$NdArray@_N@2@AEBV32@E@Z) already defined in ex1.obj 

ex1.obj : error LNK2005: "class nc::NdArray<unsigned int> __cdecl nc::find(class nc::NdArray<bool> const &,unsigned int)" (?find@nc@@YA?AV?$NdArray@I@1@AEBV?$NdArray@_N@1@I@Z) already defined in ex1.obj 

\x64\Release\ex1.exe : fatal error LNK1169: one or more multiply defined symbols 

This happens whether or not write functions or class in exutil.cpp. 
Making related functions in .hpp files inline and variables extern could fixed linking error.But I am not sure the consequences. 
What I use was the most recent version of NumCpp cloned from github.
Thanks.

**Comment by dpilger26** [comment]
Thank you for bringing this to my attention.  Re-pull on master and your problem should be fixed.
