### ISSUE TITLE
NumCpp & Qt

### ISSUE THREAD

**Issue by balebanov** [dpilger26/NumCpp#131]
Hello!

I'm making some Qt project with NumCpp library. I'm trying to use NumCpp's functions and display results of them on the UI form. 
To display something on the UI it needs to be converted to **QString** type. 

When I use this:
`    auto var = nc::random::randFloat<float>({1, 1}, 0, 100);`
`    QString str = QString::number(var);`

or like this:
`    auto var = nc::random::randFloat<float>({1, 1}, 0, 100);`
`    auto printable = QStringLiteral("Numbers: &1").arg(var);`

I've got an error: `no matching function for call to ‘QString::number(nc::NdArray<float, std::allocator<float> >&)’`. This error is displayed because QString supports only classical C-like data types: _int, float, double_ etc. 

So, is it possible to use NumCpp into Qt projects with UI? What can you advice to do in my trouble? Are there any examples of data convertions nc-types to classical C-types?
Regards

**Comment by dpilger26** [comment]
You need to use the `item()` method to get the `dtype` value out of a scaler array:

```cpp
auto var = nc::random::randFloat<float>({1, 1}, 0, 100);
QString str = QString::number(var.item());
```

and 

```cpp
auto var = nc::random::randFloat<float>({1, 1}, 0, 100);
auto printable = QStringLiteral("Numbers: &1").arg(var.item());
```

**Comment by balebanov** [comment]
Thank you! 🥇
