### ISSUE TITLE
Wrong answer in nc::linalg::inv

### ISSUE THREAD

**Issue by tatianyi** [dpilger26/NumCpp#132]
**Describe the bug**
The wrong result is obtained when calculating the inverse matrix.

**To Reproduce**
1. Let m be a 2*2 specific matrix:    `nc::NdArray<int> m = { {0, 1}, {2, 3} };`
2. Let n be the inverse matrix of m:    `auto n = nc::linalg::inv(m);`
3. Output the matrix n:    `std::cout << n << std::endl;`

**Expected behavior**
The correct answer of n should be: `[ [-1.5, 0.5], [1, 0] ]`

**Screenshots**
![wa](https://user-images.githubusercontent.com/16820733/152645816-62ce6d2f-55ce-4d11-8079-38ba70d9fab6.png)

_The cause of the problem should be here:_
![bug](https://user-images.githubusercontent.com/16820733/152645956-6f55a79f-9b16-4d97-8bd8-66f2d8ba6969.png)
_where t=0 (the first element in the matrix m)_

**Additional context**
Test platform: Microsoft Visual Studio Community 2022 (x64) 17.0.5    Debug x64
defined the macro "NUMCPP_NO_USE_BOOST" at the very beginning.
![ac](https://user-images.githubusercontent.com/16820733/152646065-1051698e-5a4c-4f15-8a98-3a7e1f209bde.png)
_This problem does not recur in NumPy._

**Comment by jpalves** [comment]
It's because pivoting is not implemented correctly,  I have made my own inv and replace, take a look. https://github.com/jpalves/NumCpp-Base/blob/main/include/NumCpp/Linalg/inv.hpp

**Comment by dpilger26** [comment]
Fixed in Version 2.8.0 release.  Thank you @jpalves.

**Comment by jpalves** [comment]
You are welcome [dpilger26](https://github.com/dpilger26)
