### ISSUE TITLE
cmake --build . --target install Error

### ISSUE THREAD

**Issue by mauricewells** [dpilger26/NumCpp#134]
when run "cmake --build . --target install", i got error message
how can i fix that error?
![image](https://user-images.githubusercontent.com/96590277/153977250-68c636d7-407a-4f78-8101-637bb334d9cf.png)

**Comment by dpilger26** [comment]
The error message is telling you that you need to open your terminal in admin mode.

**Comment by mauricewells** [comment]
thanks a lot
i solved this problem by running my terminal in admin mode.
