### ISSUE TITLE
NumCpp dons't run in Debug mode of Visual Studio 2019

### ISSUE THREAD

**Issue by mauricewells** [dpilger26/NumCpp#135]
NumCpp  run in Release mode of Visual Studio 2019 but doesn't run in Debug mode
What is the reason?
![image](https://user-images.githubusercontent.com/96590277/153990263-fe0252b6-667a-4517-9ec9-a166bd305ff4.png)

**Comment by mauricewells** [comment]
![image](https://user-images.githubusercontent.com/96590277/153990356-f8d7f683-0603-4622-abea-8315ad5e91e9.png)

**Comment by dpilger26** [comment]
I looks like you haven't added the boost includes to your debug config.

**Comment by mauricewells** [comment]
should i add boost includes?

**Comment by mauricewells** [comment]
oh, i solved, thank you
