### ISSUE TITLE
Numcpp header files are slow to load

### ISSUE THREAD

**Issue by xiang-tao** [dpilger26/NumCpp#138]
When importing the Numcpp header files, a very small code program takes about 5 to 8 seconds to run, is there any way to speed it up?

**Comment by dpilger26** [comment]
I'm not sure what you are asking?  Do you mean it is slow to run, or slow to build?

**Comment by xiang-tao** [comment]
For example, I run the following code:
```
#include <NumCpp.hpp>
#include <iostream>
using namespace std;

int main()
{
    nc::NdArray<int> a = { { 1, 2 }, { 3, 4 }, { 5, 6 } };
    cout << a << endl;
    return 0;
}
```
I am using ubuntu system and when I compile the file using g++ command in terminal it takes about 5 seconds.

But when the Numcpp header file is not imported, using the g++ command to compile the following code is completed in an instant.
```
#include <iostream>
using namespace std;

int main()
{
    int a[3][2] = { { 1, 2 }, { 3, 4 }, { 5, 6 } };
    return 0;
}
```
What I want to express is why the compilation process slows down so much after adding the Numcpp header file? Is there any way to speed up this compilation process? thanks.

**Comment by dpilger26** [comment]
The top level `NumCpp.hpp` file is a convenience header that includes the entirety of the `NumCpp` library, which is quite large.  If build time is a concern for you then you should be including only the headers that you need.  The below slight change to your example should build much faster:

```cpp
#include "NumCpp/NdArray.hpp"
#include <iostream>
using namespace std;

int main()
{
    nc::NdArray<int> a = { { 1, 2 }, { 3, 4 }, { 5, 6 } };
    cout << a << endl;
    return 0;
}
```

**Comment by xiang-tao** [comment]
I ran the code you gave and it did get a lot faster, thank you for your answer.
