### ISSUE TITLE
When compiling with NumCpp getting a lot of errors

### ISSUE THREAD

**Issue by erikthegamer1242** [dpilger26/NumCpp#140]
**Describe the bug**
Installed NumCpp latest on ArchLinux using CMake, and when building using g++ getting a lot of errors. Except for the include line, I haven't even used it anywhere inside my code.

**To Reproduce**
1. Install NumCpp using CMake
2. Include in a cpp file like this: `#include <NumCpp.hpp>`
3. Compile using g++ like this: `g++ test.cpp -o test`
4. Get errors: [log.txt](https://github.com/dpilger26/NumCpp/files/8240678/log.txt)

**Expected behavior**
Should compile normally

**Screenshots**

**Additional context**
g++ verion: g++ (GCC) 11.2.0
c++ standard used: c++14

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dpilger26** [comment]
Sorry, I'm going to need more to go on than this...?

**Comment by erikthegamer1242** [comment]
Sorry for the late response. I have since realized that it only throws the compile error if I also include Xlib like this: `#include <X11/Xlib.h>` or `#include <X11/Xutil.h>`

The whole program that I used to test this:
```C++
#include "/usr/include/opencv2/opencv.hpp"
#include "/usr/include/opencv2/core/mat.hpp"
//#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <iostream>
#include <NumCpp.hpp>

using namespace std;

int main() {
    cout << "hello World!";
}```

**Comment by dpilger26** [comment]
Ah ok.  My guess is that X11, being an old C library, probably does something like 

```cpp
#define Bool int
```

somewhere within the library.  This will clash and cause problems with a couple template types in `NumCpp`... Macros are evil!.  I'll rename that template parameter in the next release to try to avoid this type of issue in the future.

**Comment by dpilger26** [comment]
Mitigated in Version 2.8.0 release.
