### ISSUE TITLE
How can I import NumCpp into a C++ project that compiles using a Makefile?

### ISSUE THREAD

**Issue by MotorCityCobra** [dpilger26/NumCpp#141]
My current project in C++ uses a Makefile to compile, but I want to add NumCpp.
>What do I put in the Makefile to use the 'NumCpp' library?

The NumCpp CMakeLists.txt
cmake_minimum_required(VERSION 3.14)

project("HelloWorld" CXX)

add_executable(${PROJECT_NAME} main.cpp)

find_package(NumCpp 2.6.2 REQUIRED)
target_link_libraries(${PROJECT_NAME}
    NumCpp::NumCpp
)

The Makefile
COMMON=/O2 /MT /EHsc /arch:AVX /I../include /Fe../bin/
cl_vars = 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\Hostx86\x86\cl.exe'
cl_var = 'cl'
all:
    $(cl_var) $(COMMON) testxml.cc                 ../bin/mujoco210nogl.lib
    $(cl_var) $(COMMON) testspeed.cc               ../bin/mujoco210nogl.lib
    $(cl_var) $(COMMON) compile.cc                 ../bin/mujoco210nogl.lib
    $(cl_var) $(COMMON) derivative.cc /openmp      ../bin/mujoco210nogl.lib
    $(cl_var) $(COMMON) basic.cc ../bin/glfw3.lib  ../bin/mujoco210.lib
    $(cl_var) $(COMMON) record.cc ../bin/glfw3.lib ../bin/mujoco210.lib
    $(cl_var) $(COMMON) simulate.cc ../include/uitools.c ../bin/glfw3.lib ../bin/mujoco210.lib
    del *.obj

**Comment by dpilger26** [comment]
It is a header only library so you just need to add an include directive pointing to the library:
`-I<path to NumCpp include dir>`
