### ISSUE TITLE
Is it possible to use interp with lists?

### ISSUE THREAD

**Issue by MotorCityCobra** [dpilger26/NumCpp#142]
In Python I use lists in numpy.interp, like this...

`epsilon = np.interp(1, [0, 100], [1, 0.001])`

I tried,
```
double arr4[] = { 0, 100 };
double arr5[] = { 1, 0.001 };

auto a = nc::interp(1, arr4, arr5);
std::cout << a;
```

I get errors.  

```
simulate.cc(285): error C2672: 'nc::interp': no matching overloaded function found
simulate.cc(285): error C2784: 'nc::NdArray<dtype,std::allocator<_Ty>> nc::interp(const nc::NdArray<dtype,std::allocator<_Ty>> &,const nc::NdArray<dtype,std::allocator<_Ty>> &,const nc::NdArray<dtype,std::allocator<_Ty>> &)': could not deduce template argument for 'const nc::NdArray<dtype,std::allocator<_Ty>> &' from 'int'
```  

Thank you.

**Comment by dpilger26** [comment]
See the documentation for `interp()` [here](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#a25a0717dab4a33f74927d390b83182ab).

```cpp
nc::NdArray<double> arr4 = {0, 100};
nc::NdArray<double> arr5 = {1, 0.001};

auto a = nc::interp({1}, arr4, arr5);
std::cout << a.item() << '\n';
```

**Comment by MotorCityCobra** [comment]
Thank you so much.
I must have missed the docs. I didn't know there were any.

I was dreading using using C++ without Numpy. Thank you.

**Comment by MotorCityCobra** [comment]
@dpilger26 
Sorry, I know this is a rookie C++ question, but how do I format the value for the epsilon number and plug in a number I can increment?  
The value I'm talking about is the `{1}` from your example.  

You wrote,
`auto a = nc::interp({1}, arr4, arr5);`


I want to do something like ...  

```
nc::NdArray<double> arr4 = {0, 100};
nc::NdArray<double> arr5 = {1, 0.001};
int eps = 1;  

int main()
{
    while (1)
    {
        eps++;
        auto a = nc::interp({eps}, arr4, arr5);
        std::cout << a.item() << " this is the interp function" << "\n";
    }
}
```

I'm getting the error,
```
simulate.cc(296): error C2398: Element '1': conversion from 'int' to 'dtype' requires a narrowing conversion
        with
        [
            dtype=double
        ]
Generating Code...
Compiling...
uitools.c
Generating Code...
make: *** [Makefile:14: all] Error 2
```

**Comment by dpilger26** [comment]
It requires for all of the input NdArrays to be the same dtype. So you
probably need to wrap your eps in a static_cast<double>(eps).
