### ISSUE TITLE
Multiply with BroadCasting. e.g. shape: [1,3] * [2,1] => [2 * 3]

### ISSUE THREAD

**Issue by ValkyriaLenneth** [dpilger26/NumCpp#147]
Thanks for you project.
But I found that the broadcasting in numpy is likely not supported in NumCpp.
For example, I have two matrixs:
A=[1,2,3]
B = [[1], [2], [3]]
In numpy, A * B is 
[ [1,2,3], 
 [2,4,6],
 [3,6,9]]
However, in NumCpp, the error occured. 
Thus I want to ask that are the shapes of two matrixs must be the same in NumCpp?

**Comment by dpilger26** [comment]
Added in Release Version 2.10.0.
