### ISSUE TITLE
numpy.take

### ISSUE THREAD

**Issue by TuskAW** [dpilger26/NumCpp#149]
I looked through the code looking for the equivalent call for numpy.take. Does that function exist in the library?

Thanks,

James

**Comment by dpilger26** [comment]
You can achieve the same thing using the `NdArray` access operators. 

The equivalent to 
```python
np.take(a, indices)
```
would be
```cpp
a[indices]
```

The equivalent to 
```python
np.take(a, indices, axis=0)
```
would be
```cpp
a[indices, a.colSlice()]
```

The equivalent to 
```python
np.take(a, indices, axis=1)
```
would be
```cpp
a[a.rowSlice(), indices]
```

I'll add `take()` to the next release.

**Comment by dpilger26** [comment]
Added to Version 2.8.0 release.

**Comment by TuskAW** [comment]
Thank you!!!
