### ISSUE TITLE
Is the file format of NumCpp differs from numpy in python?

### ISSUE THREAD

**Issue by yujincheng** [dpilger26/NumCpp#15]
I dump the array in numpy use a.dump("test.bin"). Yet I can not recover the array in NumCpp with auto a = nc::load<flaot>("test.bin") .
Is the file format of NumCpp differs from numpy in python?

**Comment by dpilger26** [comment]
Sorry for the confusion.  No the file formats are not the same.  NumPy uses pickle for its dump/save and load functions.  NumCpp writes its arrays in a flat binary format.  If you would like to read in a NumCpp dumped file with NumPy then you should use NumPy's fromfile function.  eg. 
```
#include "NumCpp.hpp"

int main()
{
    nc::NdArray<nc::int32> a = { {0, -1, -2}, {0, 1, 2}};
    a.dump("C:/Temp/test.bin");
    return 0;
}
```
Then from python
```
a = np.fromfile(r'C:\Temp\test.bin', dtype=np.int32).reshape([2,3])
```
