### ISSUE TITLE
Compilation error caused by <version> header

### ISSUE THREAD

**Issue by toge** [dpilger26/NumCpp#151]
**Describe the bug**

Compilation error NumCpp 2.8.0 in GCC 5.

**To Reproduce**

Please try to compile NumCpp 2.8.0 by GCC 5.4.

**Expected behavior**

Success to compile NumCpp 2.8.0.

**Additional context**

In include/NumCpp/Core/Internal/StlAlgorithms.hpp, 
`<version>` header is included since NumCpp 2.8.0.

As you know, the `<version>` header has been supported since C++20.
https://en.cppreference.com/w/cpp/header/version

Does NumCpp require C++20 since 2.8.0?

**Comment by dpilger26** [comment]
Requiring C++20 was not the intension, just an oversight.  I've removed the `<version>` header and re-pushed to master, as well as updated the Version 2.8.0 release package.

**Comment by toge** [comment]
Thank you for quick response!
