### ISSUE TITLE
Update it in vcpkg, last version of NumCpp in vcpkg is 2.6.0, update the latest one to vcpkg please

### ISSUE THREAD

**Issue by Rablidad** [dpilger26/NumCpp#158]
**Describe the solution you'd like**
Update the new 2.8.0 version to vcpkg, the current version available in vcpkg is only 2.6.0 from the last year (2021)

**Comment by dpilger26** [comment]
Opened a new issue against Vcpkg 

https://github.com/microsoft/vcpkg/issues/26476

**Comment by Rablidad** [comment]
> Opened a new issue against Vcpkg
> 
> [microsoft/vcpkg#26476](https://github.com/microsoft/vcpkg/issues/26476)

Nice! thank you very much!

**Comment by dpilger26** [comment]
Closed to
 https://github.com/microsoft/vcpkg/pull/26482
