### ISSUE TITLE
Slow down after converting the numCPP from the numpy

### ISSUE THREAD

**Issue by HyungJoo-Kwon** [dpilger26/NumCpp#159]
Hi, I have a question.

test_array   :   10000 x 10000 double array
test_D   :   10000 x 10000 double array

Case 1
    Numpy   :  test_array [ test_D < 0.2 ] = 1.0
    NumCpp  :  test_array.putMask ( test_D < 0.2 , 1.0 );
                       test_array.putMask ( test_D >= 0.2 , 0.0 );

Case 2 
    Numpy   :  test_array = test_array / np.dot(np.sum(test_array , axis=1, keepdims=True), np.ones((1, test_array .shape[0])))
    NumCpp  :      test_array = test_array / nc::dot(nc::sum(test_array , nc::Axis::COL).reshape(test_array.shaep().rows, 1), nc::ones<double>(1, test_array .shape().rows));

As in the case above, it slowed down after the code was converted code.
Case 1 is increased from about 1 second to 5 seconds.
Case 2 is increased from about 1 second to 15 seconds.
Is there any other way to improve the speed?
Or is there a better code?

**Comment by dpilger26** [comment]
I tried your examples with significantly different results than you...

```cpp
#include "NumCpp.hpp"

#include <cstdlib>

int main()
{
    constexpr nc::uint32 NUM_ROWS = 10000;
    constexpr nc::uint32 NUM_COLS = 10000;

    auto timer1 = nc::Timer<std::chrono::milliseconds>("Case 1");
    auto timer2 = nc::Timer<std::chrono::milliseconds>("Case 2");

    auto test_array = nc::random::randN<double>({ NUM_ROWS, NUM_COLS });

    timer1.tic();
    test_array.putMask(test_array < 0.2, 0.0);
    timer1.toc();

    timer2.tic();
    test_array = test_array / nc::dot(nc::sum(test_array, nc::Axis::COL).reshape(test_array.shape().rows, 1),
                                      nc::ones<double>(1, test_array.shape().rows));
    timer2.toc();

    return EXIT_SUCCESS;
}
```

I built with Clang 14 and ran on an AMD Ryzen 7 3800X, which outputs:

```bash
Case 1 Elapsed Time = 711 milliseconds
Case 2 Elapsed Time = 1607 milliseconds
```

Are you perhaps compiling in debug mode, or no optimizations?

**Comment by HyungJoo-Kwon** [comment]
Thank you so much
I was always testing in debug mode.
I wasn't checking this part.
