### ISSUE TITLE
Use both NumCpp and Numpy

### ISSUE THREAD

**Issue by 023proz** [dpilger26/NumCpp#16]
I have built a Dynamic-link library using NumCpp and then used Python to call this dll file, in my Python code, the array is in Numpy, so how can I pass Numpy array into the NumCpp API?

The API in my C++ code is defined as follows:
```cpp
#define MATHLIBRARY_API __declspec(dllexport)

extern "C"  MATHLIBRARY_API
NdArray<double> cpp_double_dot(const NdArray<double>& inArray1, const NdArray<double>& inArray2);
```
```cpp
NdArray<double> cpp_double_dot(const NdArray<double>& inArray1, const NdArray<double>& inArray2) {
	return dot<double>(inArray1, inArray2);
}
```
Then I made the dll file with name "NumCpp.dll".

And in the Python, is as follows:
```Python
test = cdll.LoadLibrary('NumCpp.dll')
vector_a = np.array([[1, 4], [5, 6]]) 
vector_b = np.array([[2, 4], [5, 2]]) 
print (test.cpp_double_dot(vector_a, vector_b))
```
But the API complains that 
```
ctypes.ArgumentError: argument 1: <class 'TypeError'>: Don't know how to convert parameter 1
```

So I want to know can I use NumCpp and NumPy together?
Looking forward to your help!
Thanks very much!

**Comment by dpilger26** [comment]
I would recommend using [pybind11](https://github.com/pybind/pybind11) and NumCpp's [pybind11](https://github.com/pybind/pybind11) interface.  [Pybind11 ](https://github.com/pybind/pybind11) is an excellent library for binding C++ code as a .dll/.so for running in Python.  See their [full documentation](https://pybind11.readthedocs.io/en/master/) for everything that can be done.

Here is a code snippet to demonstrate your example.  Be sure to compile with the preprocessor definitions **INCLUDE_PYTHON_INTERFACE** and **INCLUDE_PYBIND_PYTHON_INTERFACE** to gain access to the interface functions.
```c++
#include "pybind11/pybind11.h"
#include "pybind11/numpy.h"

#include "NumCpp.hpp"

namespace py=pybind11;

template<typename T>
py::array_t<double> cpp_dot(py::array_t<T, py::array::c_style> inArray1, py::array_t<T, py::array::c_style> inArray2)
{
    auto array1 = nc::pybind2nc(inArray1);
    auto array2 = nc::pybind2nc(inArray2);
    auto dotProduct = nc::dot<double>(array1, array2);
    return nc::nc2pybind(dotProduct);
}

PYBIND11_MODULE(NumCpp, m)
{
    m.doc() = "This is an example of using NumCpp with python and NumPy.";

    m.def("cpp_dot_double", &cpp_dot<double>,
        pybind11::arg("inArray1"),
        pybind11::arg("inArray2"),
        "Returns the dot project of the two arrays.");
}
```
Then on the Python side:
```python
import numpy as np
import NumCpp

vector_a = np.array([[1, 4], [5, 6]]) 
vector_b = np.array([[2, 4], [5, 2]])

vector_c = NumCpp.cpp_dot_double(vector_a, vector_b)
```
which gives the output:
```python
array([[22., 12.], [40., 32.]])
```

**Comment by 023proz** [comment]
WOW, such a great answer.
Thanks very much!
I'll try it.
