### ISSUE TITLE
Performance of NumCpp

### ISSUE THREAD

**Issue by 023proz** [dpilger26/NumCpp#17]
I found for matrix dot production, the run-time of NumPy and NumCpp have a very big difference, the former is much quicker. I'm so curious about that.

For my testing, I have a PC with I7 8700K. 
I run the C++ code with VS2019, Release X64.  The runtime is 3.772 second.
Here is my test C++ code.
```cpp
auto x = nc::arange<double>(1000000);
x.reshape(1000, 1000);
auto y = nc::arange<double>(1000000);
y.reshape(1000, 1000);
	
std::clock_t start;
double duration;
start = std::clock();

auto z = nc::dot<double>(x, y);

duration = (std::clock() - start) / (double)CLOCKS_PER_SEC;
cout << "NumCpp: " << duration << endl;
```

I run the Python just with the command line, the run time is just 0.012s.
Here is my test Python code.
```Python
x = np.arange(1000000.).reshape((1000, 1000)) 
y = np.arange(1000000.).reshape((1000, 1000)) 
s2 = time.time()
c = np.dot(x, y)
e2 = time.time()
print ("numpy: ", str(e2 - s2))
```

For all of my tests, I tested for several times and checked the output. 
Can you please explain why there exists such a big performance gap? Especially the C++ one is much slower, it so counter-intuitive...
Thanks very much!

**Comment by dpilger26** [comment]
**NumCpp** uses the standard algorithm for matrix multiplication as explained [here](https://www.geeksforgeeks.org/c-program-multiply-two-matrices/).  **NumPy** is using a [BLAS](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms) backend for linear algebra operations, which is highly optimized for the hardware it is running on.  

I had a couple of design goals when I was putting together **NumCpp**.  One was to be header only for ease of use, and the other was to minimize the need to install and link in too many other third party libraries.  With these goals in mind, it is very difficult to incorporate a BLAS/LAPACK backend, but it is something that is on my mind for future upgrades.  

If you have ideas or would like to help with future optimizations to this library I would welcome the help.  For now I did implement a few small cache type optimizations to dot() that on my computer resulted in a 2x-4x speed up for large matrices.  I know this still doesn't approach **NumPy's** performance, but it helps.

**Comment by 023proz** [comment]
Thanks, David!
I really appreciate your kind help and explanation.
I'm really interested in programming with C++ and do some optimizations with the codes.
I think maybe I can join your project and then contribute it together!

**Comment by angon823** [comment]
> **NumCpp** uses the standard algorithm for matrix multiplication as explained [here](https://www.geeksforgeeks.org/c-program-multiply-two-matrices/). **NumPy** is using a [BLAS](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms) backend for linear algebra operations, which is highly optimized for the hardware it is running on.
> 
> I had a couple of design goals when I was putting together **NumCpp**. One was to be header only for ease of use, and the other was to minimize the need to install and link in too many other third party libraries. With these goals in mind, it is very difficult to incorporate a BLAS/LAPACK backend, but it is something that is on my mind for future upgrades.
> 
> If you have ideas or would like to help with future optimizations to this library I would welcome the help. For now I did implement a few small cache type optimizations to dot() that on my computer resulted in a 2x-4x speed up for large matrices. I know this still doesn't approach **NumPy's** performance, but it helps.

You can consider using openmp to optimize matrix multiplication, because the installation of openmp on Windows is very convenient, and it is an option, it can work the same even without openmp installed.

#pragma omp parallel for(4)    on my computer resulted in a 2x-4x speed up for large matrices.

**Comment by dpilger26** [comment]
@angon823 thanks for the input.  I had stuck in some more optimizations to dot() a while back that actually has NumCpp performance on par with NumPy now.
