### ISSUE TITLE
Update all rows in particular column in NdArray

### ISSUE THREAD

**Issue by serhii-vlasiuk** [dpilger26/NumCpp#172]
I have nc::NdArray<float> like:
[a   b   c    d]
[a1 b1  c1  d1]
[a2 b2 c2 d2]
[a3 b3 c3 d3]

Is it possible to update all rows for first or other columns?
And get the following result:
[a_new   b   c    d]
[a_new1 b1  c1  d1]
[a_new2 b2 c2 d2]
[a_new3 b3 c3 d3]

**Comment by dpilger26** [comment]
There are a lot of overloads of the `NdArray` `put()` method for inserting values. Specifically you'll want this [one](https://dpilger26.github.io/NumCpp/doxygen/html/classnc_1_1_nd_array.html#af062cf00ee693dbd74d0f440b1cbded7)

```cpp
arr.put(arr.rSlice(), 0, values);
```
