### ISSUE TITLE
reshape (3, 4, 2)

### ISSUE THREAD

**Issue by serhii-vlasiuk** [dpilger26/NumCpp#175]
Is it possible to do reshape like this?

Python code:
arr = np.reshape(arr, (3, 4, 2))  # 3 means it will have 3 parent list that has a structure of (4, 2)

print(arr) # prints '[  [[ 0  1] [ 2  3] [ 4  5] [ 6  7]]    [[ 8  9] [10 11] [12 13] [14 15]]    [[16 17] [18 19] [20 21] [22 23]]  ]'

**Comment by dpilger26** [comment]
No, this is not possible.
