### ISSUE TITLE
There is a compilation error when I use numcpp.

### ISSUE THREAD

**Issue by menglei5633** [dpilger26/NumCpp#18]
.\Numcpp_include/NumCpp/Vector/Vec3.hpp:271:38: error: no matching function for call to 'hypot(const double&, const double&, const double&)'
             return std::hypot(x, y, z);

**Comment by menglei5633** [comment]
my gcc version is 8.2.0

**Comment by dpilger26** [comment]
The overload of std::hypot with three inputs is a new addition to the C++17 standard.  I was originally using it without realizing that detail.  I had actually already changed this in my develop branch, but I'm working on some other pretty major updates there and not quite ready to merge to master yet.  For the meantime I changed that function on master so do a pull and you should be good.

**Comment by Nucs** [comment]
@dpilger26, May I ask what that update will include?

**Comment by dpilger26** [comment]
@Nucs 

The update will include several things:
1) Breaking up most classes and functions into their own files so they can be included individually for faster compile times.  You will still be able to include the main NumCpp.hpp header to have access to everything.
2) Beefing up the polynomial namespace 
3) Adding a special functions namespace with a whole slew of new functions
4) Reworking the random namespace interface a bit, should be easier to use
5) Other more minor bugs/compiler warnings across C++ standards and different compilers
