### ISSUE TITLE
`a > 0` io `a > 5` in README.md

### ISSUE THREAD

**Issue by jamadagni** [dpilger26/NumCpp#186]
Hello. In the README.md, under https://github.com/dpilger26/NumCpp#slicingbroadcasting there is the entry:

| numpy | numcpp |
| --- | --- |
| a[a > 5] | a[a > 0] |

Is there a reason for the C++ version to read `a > 0` rather than `a > 5`? I ask because all other equivalents seem totally equivalent even in the example values but this one is different.

**Comment by dpilger26** [comment]
No reason, just a typo/oversight. I'll get that fixed.
