### ISSUE TITLE
reshape() should return a new copy instead of modifying

### ISSUE THREAD

**Issue by TorokLev** [dpilger26/NumCpp#193]
**Is your feature request related to a problem? Please describe.**

reshape modifies the input but numpy doesn't. It would desirable to behave similar.

**Describe the solution you'd like**

It should not break:

const nc::NdArray<double> array = {1,2,3};
std::cout << array.reshape(-1,1).shape();

**Describe alternatives you've considered**

**Additional context**

**Comment by dpilger26** [comment]
I disagree, the goal of this library is to be `NumPy` _like_, but not necessarily identical. It is more efficient for the default behavior to be an in place reshape and to let the user call the `copy()` method if they need a copy.  I've updated the documentation to be more clear and to reflect this.
