### ISSUE TITLE
nc::append should be able to operate empty NdArray<> too. 

### ISSUE THREAD

**Issue by TorokLev** [dpilger26/NumCpp#194]
**Is your feature request related to a problem? Please describe.**

In Python it looks like this:

    collector = np.array([])
    np.append(collector, 3)

it should look similar in C++

    #include <NumCpp.hpp>
    nc::NdArray<double> collector;
    nc::append( collector, {3});

but it breaks since collector is empty.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dpilger26** [comment]
Implemented as part of release version 2.11.0.
