### ISSUE TITLE
nc::stack, hstack, vstack operates on std::initialier_list<> only.

### ISSUE THREAD

**Issue by TorokLev** [dpilger26/NumCpp#196]
**Describe the bug**

Due to its definition it is impossible to stack dynamically anything.
So it makes it completely useless

**To Reproduce**

#include <NumCpp.hpp>
std::list<nc::NdArray<double>> ll;
ll.push_back({10,2,3,4});
nc::hstack(ll);  //  fails here

**Expected behavior**

not failing.

**Comment by dpilger26** [comment]
Implemented as part of release version 2.11.0.
