### ISSUE TITLE
Is there some method to transform torch::Tensor to nc::NdArray, nc::NdArray to torch::Tensor?

### ISSUE THREAD

**Issue by planckztd** [dpilger26/NumCpp#20]
you know ,in pytorch,  use `tensor.numpy()` transform to tensor and`torch.Tensor(numpy)`transform to numpy. Is there any method to  transform torch::Tensor to nc::NdArray? or nc::NdArray to torch::Tensor

**Comment by dpilger26** [comment]
No, NumCpp does not have built in support for converting to/from torch::Tensor.  nc::NdArray does however provide methods for accessing/working with the underlying data pointer [data(), & dataRelease()] that can be passed to a torch::Tensor constructor.  Likewise, torch::Tensor also provides methods for accessing it's underlying data pointer [data(), dataPtr()] and that can be passed to an nc::NdArray constructor.
