### ISSUE TITLE
Memory Leak in NdArray

### ISSUE THREAD

**Issue by jzylkin** [dpilger26/NumCpp#207]
**Describe the bug**
The NdArray<> class can allocate memory to create the underlying `_array` using std:allocator, but its destructor does not deallocate this memory.

**To Reproduce**
1. Create an NdArray object on the stack using the constructor that takes a size and shape.
2. Observe that memory is allocated on the heap for this array.
3. After the NdArray object goes out of scope, the memory is not freed.

**Expected behavior**
I expect the NdArray object to clean up the memory it creates when it is destroyed.

**Comment by dpilger26** [comment]
Not sure what you are talking about?  The `NdArray` destructor calls `deleteArray()` which deallocates the heap memory.

```cpp
void deleteArray() noexcept
{
    if (ownsPtr_ && array_ != nullptr)
    {
        allocator_.deallocate(array_, size_);
    }

    array_      = nullptr;
    shape_.rows = shape_.cols = 0;
    size_                     = 0;
    ownsPtr_                  = false;
    endianess_                = Endian::NATIVE;
}
```

**Comment by jzylkin** [comment]
Hi David,

I was looking at an older release from this February. I did not realize you
fixed this already. Thanks for getting back to me!

Jack
