### ISSUE TITLE
Is there a "savetxt()/loadtxt()" function like in numpy?

### ISSUE THREAD

**Issue by msnh2012** [dpilger26/NumCpp#22]

**Comment by dpilger26** [comment]
No NumCpp does not have the generalized savetxt() and loadtxt() functions.  It does however have the less general tofile() and fromfile() functions that can be used to write out either binary or text files.  See the following example for writing/reading a tab separated value text file.
```
#include "NumCpp.hpp"

#include <iostream>
#include <string>

int main()
{
    // random data
    auto data = nc::random::randInt<int>({ 10, 10 }, 0, 100);

    // write the data to a text file
    const std::string filename = "C:/Temp/data.txt";
    const std::string seperator = "\t"; // TSV
    data.tofile(filename, seperator);

    // read the data back in
    auto dataRead = nc::fromfile<int>(filename, seperator);
    dataRead.reshape(data.shape());

    // sanity check that it is the same
    if (nc::array_equal(dataRead, data))
    {
        std::cout << "Arrays are equal" << std::endl;
    }
    else
    {
        std::cout << "Arrays are NOT equal" << std::endl;
    }

    return 0;
}
```
Be sure to do a pull on master to get the most up-to-date code.  I discovered and fixed a small bug with fromfile() while putting together this example...

**Comment by msnh2012** [comment]
Thanks! If it can get the shape of data , that will be really nice.
