### ISSUE TITLE
can stack function change the input parameter type to list or vector?

### ISSUE THREAD

**Issue by novioleo** [dpilger26/NumCpp#24]
i'm try to use `vstack` to stack a series `ndarray`,but the size of series is uncertain and the `initializer_list` can't convert from `vector` or `list`.
so,can i change the implement of the stack function?

**Comment by dpilger26** [comment]
Can you post some example code of what you are trying to do that isn't working?  

In order for any of the stack methods to work, the NdArray dimensions of the opposite the stack axis need to be the same.  For example: vstack of arrays of shape [3, 4] and [4, 3] will not work since the two arrays have a different number of columns.

**Comment by novioleo** [comment]
@dpilger26 glad for your rely.
i think you have misunderstand my question.
i mean is there any possibility to use `vector` or `list` to replace `initializer_list`?

**Comment by dpilger26** [comment]
I wouldn't want to replace `initializer_list` as I would still want the capability to write something like
`auto d = nc::vstack({a, b, c});`. 
However I could add an overload to the stack methods to take in a `vector` of `NdArray` and stack them accordingly.  Am I understanding you correctly now?

**Comment by novioleo** [comment]
@dpilger26 you are right...
i just try to figure out why you not imple it~~~~

**Comment by dpilger26** [comment]
It is pretty impossible to think of every which way a user may want to use a library... If you would like to request a new feature then go ahead and do so.  If you would like to implement the new feature yourself and do a pull request I'll be happy to review it.  Or if you would like to fork the repo and do whatever you want that is fine too.  That is the beauty of open source.

**Comment by novioleo** [comment]
you are right.tks so much.and i think you can close this issue.


 
---Original---
