### ISSUE TITLE
svd is so slow.

### ISSUE THREAD

**Issue by novioleo** [dpilger26/NumCpp#26]
i tried the svd in numcpp and numpy,the same size of ndarray,the numcpp is slower than numpy about 5 times.

**Comment by dpilger26** [comment]
That doesn't really surprise me.  For larger arrays a "divide and conquer" approach can yield much faster processing times, unfortunately though i have not implemented that.  

At any rate, performance of NumCpp vs NumPy is not really an issue in the GitHub sense.  If NumCpp is fast enough for what you need to do then don't worry about it.  It you have decided/proven that NumCpp's SVD is indeed a bottle neck in your processing that you need to speed up then you have two options;  Either help to improve NumCpp, or use another library.  The Eigen library has a very good implementation of SVD.

**Comment by novioleo** [comment]
@dpilger26 thks for your reply

**Comment by wolfv** [comment]
Hi @novioleo we have a library called `xtensor` and `xtensor-blas` has SVD that uses the same algorithm as NumPy (called LAPACK) that should be just as fast. 

`xtensor` also follows other ideas of NumPy (you can check out our cheatsheet over here: https://xtensor.readthedocs.io/en/latest/numpy.html

**Comment by novioleo** [comment]
@wolfv so great.i'll have a try.
