### ISSUE TITLE
how to use library in C++

### ISSUE THREAD

**Issue by imohammad74** [dpilger26/NumCpp#3]
Hi, i'm beginner in C++, and search in the web about install and use library's C++, but  i don't find a good tutorial.
can you help me how use your library ?

Thanks

**Comment by dpilger26** [comment]
There is nothing to install. Just add the /src directory to your project's
include path, then include NumCpp.hpp in any file you want to use NumCpp.

-David

**Comment by hly92711** [comment]
sorry, I can not find the /src directory

**Comment by dpilger26** [comment]
/src was changed to /include to be consistent.
