### ISSUE TITLE
nc::floor() problem

### ISSUE THREAD

**Issue by DmitryDemidov80** [dpilger26/NumCpp#32]
Hi!
I try:
```
nc::NdArray<float> b1({2.3, -3.2, -5.8});
nc::NdArray<float> b2(1, 3);
b2=nc::floor(b1); // must be 2, -4, -6
```
but get error:  could not convert ‘returnArray’ from ‘nc::NdArray<double>’ to ‘nc::NdArray<float>’
return returnArray;

If i set b1 and b2 as double - ok.
nc::floor() returns ```nc::NdArray<double>``` instead ```nc::NdArray<dtype>```
Thanks!

**Comment by dpilger26** [comment]
Thank you for pointing this out.  The master branch has been updated with the fix.
