### ISSUE TITLE
How to set row values from array to another array?

### ISSUE THREAD

**Issue by DmitryDemidov80** [dpilger26/NumCpp#33]
Hi
I try:
```
nc::NdArray<uint16_t> a1({{1,2,3}, {4,5,6}});
nc::NdArray<uint16_t> a2(2,3); // {{0,0,0}, {0,0,0}}
auto val0=a1.at(0, nc::Slice(0, a1.numCols())); // 1,2,3
a2(0, nc::Slice(0, a2.numCols())) = val0; // must be {{1,2,3}, {0,0,0}}
//or this:
a2.at(0, nc::Slice(0, a2.numCols())) = val0;
```
but failed.
What i'm doing wrong?
Thanks!

**Comment by dpilger26** [comment]
You need to use the put() methods of NdArray to insert values.
https://dpilger26.github.io/NumCpp/doxygen/html/classnc_1_1_nd_array.html#afe758ef8867d56964efc5a67bf17e726

Here is how you would accomplish the above example:
```cpp
#include "NumCpp.hpp"

int main()
{
    nc::NdArray<nc::uint16> a1 = {{1,2,3}, {4,5,6}};
    nc::NdArray<nc::uint16> a2(2, 3);
    // need to set the array equal to zero.  Values are not defaulted to zero at construction!
    a2 = 0; // [[0, 0, 0], [0, 0, 0]]

    auto val0 = a1(0, a1.cSlice()); // [[1, 2, 3]]

    // Need to use the put() methods to insert values into an NdArray
    a2.put(0, a2.cSlice(), val0); 
    std::cout << a2; // [[1, 2, 3], [0, 0, 0]]

    return 0;
}
```

**Comment by DmitryDemidov80** [comment]
Ok, thanks!
It works.
But if i want get:
```a2 // [[1, 2, 3], [1, 2, 3]]```

i do:
```
a2.put(a2.rSlice(), a2.cSlice(), val0); 
```
and get exception "Input indices do not match values dimensions."
How to get it?
I don't want use loop like this:
```
for(int i=0; i<2; ++i)
    a2.put(i, a2.cSlice(), val0);
```

**Comment by dpilger26** [comment]
Right now putting it in a loop like you have is the way to do it.  It may be a little more typing but I feel like the intent is much clearer that way anyway.  I will look into adding more put() overloads/functionality to accomplish what your first method.
