### ISSUE TITLE
Saving function

### ISSUE THREAD

**Issue by lzied** [dpilger26/NumCpp#34]
Hi,

Do this library got a function for saving as a numpy file ?
If not, do i have an another alternative to save a numpy array with a C++ ?
Thanks.

**Comment by dpilger26** [comment]
NumCpp does not support writing out .npy files.  NumCpp does support writing arrays out as flat binary files, or text files.  See the [tofile()](https://dpilger26.github.io/NumCpp/doxygen/html/classnc_1_1_nd_array.html#aa94662d12c0f3558fa78344c8cfe95cd) NdArray method.  A file written out from NumCpp using tofile() can be read in with NumPy using the [np.fromfile()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fromfile.html) function.  

See Issue #15 for an example.  The example uses the [dump()](https://dpilger26.github.io/NumCpp/doxygen/html/classnc_1_1_nd_array.html#a1a75a88440cb5460da17b23e0dd6b030) method which is also called inside the tofile() method if saving to a binary format.
