### ISSUE TITLE
where is install and build step in ubuntu and windows

### ISSUE THREAD

**Issue by fatalfeel** [dpilger26/NumCpp#35]
where is install and build step in ubuntu and windows

**Comment by dpilger26** [comment]
It is a header only library. Just add /include to your projects include directories and you're good to go!

**Comment by dpilger26** [comment]
I went ahead and added installation instructions in /install, as well as a cmake file for installing on Linux or Windows Cygwin/MinGW.

**Comment by fatalfeel** [comment]
thanks man

**Comment by fatalfeel** [comment]
like this
https://shengyu7697.github.io/blog/2019/04/18/%E5%9C%A8-Ubuntu-%E4%B8%8B%E7%B7%A8%E8%AD%AF%E5%AE%89%E8%A3%9D-Boost-1-70-0/

**Comment by dpilger26** [comment]
Yes I would recommend your second link. I've tested with versions 1.68 and 1.70. The newest version is 1.71, which I haven't tested yet but it will likely work just fine as well.
