### ISSUE TITLE
Accessing the rows and columns of an Ndarray

### ISSUE THREAD

**Issue by Houman-HM** [dpilger26/NumCpp#37]
Hey,
I've been trying to access the rows and columns of my 2D array using [i,j] and replace its values with some other values, however, it seems that Ndarray doesn't support neither X[i,j] (which works in python) nor X[i][j] ways of accessing elements. It seems that the array is considered 1D and if I want to reach the X[1][2] element in a 3*3 array for example, I should access it as X[5]. Am I wrong? I was wondering if you could tell me how I can access the rows and columns of an Ndarray like X[i][j].

Thanks in advance!

**Comment by dpilger26** [comment]
In NumCpp operator[] is used for flattened array access as you've found.  C++ does not allow for more than one input into operator[], therefore for 2d access into an NdArray you need to use operator().  See the NumCpp docs for operator() [here](https://dpilger26.github.io/NumCpp/doxygen/html/classnc_1_1_nd_array.html#aa1c1a56d402b0f43745c075ff42f5bcb).  Here is a quick little example of how to access/set NdArray elements using the 2d operator() method:

```cpp
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>

int main()
{
    auto data = nc::NdArray<int>(5, 5);
    for (auto i = 0u; i < data.numRows(); ++i)
    {
        for (auto j = 0u; j < data.numCols(); ++j)
        {
            data(i, j) = i + j;
        }
    }

    for (auto value : data)
    {
        std::cout << value << " ";
    }

    return EXIT_SUCCESS;
}
```

**Comment by Houman-HM** [comment]
> In NumCpp operator[] is used for flattened array access as you've found. C++ does not allow for more than one input into operator[], therefore for 2d access into an NdArray you need to use operator(). See the NumCpp docs for operator() [here](https://dpilger26.github.io/NumCpp/doxygen/html/classnc_1_1_nd_array.html#aa1c1a56d402b0f43745c075ff42f5bcb). Here is a quick little example of how to access/set NdArray elements using the 2d operator() method:
> 
> ```c++
> #include "NumCpp.hpp"
> 
> #include <cstdlib>
> #include <iostream>
> 
> int main()
> {
>     auto data = nc::NdArray<int>(5, 5);
>     for (auto i = 0u; i < data.numRows(); ++i)
>     {
>         for (auto j = 0u; j < data.numCols(); ++j)
>         {
>             data(i, j) = i + j;
>         }
>     }
> 
>     for (auto value : data)
>     {
>         std::cout << value << " ";
>     }
> 
>     return EXIT_SUCCESS;
> }
> ```
Thanks for the help!
