### ISSUE TITLE
Shallow copy of memory when slicing

### ISSUE THREAD

**Issue by chinalufei** [dpilger26/NumCpp#38]
in python:
a = np.array([[1,2,3,4,5],[5,4,3,2,1]])
b = a[0:2,1:3]
b*=2
so:
b:
[[4, 6],
       [8, 6]]
a:
[[1, 4, 6, 4, 5],
       [5, 8, 6, 2, 1]]
or:

b[:]=b/4
>>> b
array([[1, 1],
       [2, 1]])
>>> a
array([[1, 1, 1, 4, 5],
       [5, 2, 1, 2, 1]])
but in numcpp:
nc::NdArray<int> a = { {1,2,3,4,5},
                            {5,4,3,2,1}
                            };
auto b = a(nc::Slice(0, 2), nc::Slice(1, 3));
b*=2
b:
[[4, 6],
       [8, 6]]
a:
[[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]]

or:

b[b.rSlice()] = b/4;
b:
[[1, 1],
       [2, 1]]
a:
[[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]]

**Comment by dpilger26** [comment]
Yes that is correct.  NumCpp differs from NumPy in this regard in that NumCpp slicing operations return copies of the elements, not references.  This is on a to-do list for me to look into changing in a future update.  I'll leave this issue open until that work is done, or I decide against that change.
