### ISSUE TITLE
how to convert nc::nonzero(a) to np.nonzero(a)

### ISSUE THREAD

**Issue by ShaneYS** [dpilger26/NumCpp#39]
a = array([[0, 1, 0, 0, 1, 1, 0],
       [1, 0, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 1]])

in numpy, np.nonzero(a) returns: (array([0, 0, 0, 1, 1, 2, 2, 2]), array([1, 4, 5, 0, 2, 1, 2, 6])).
in numcpp, nc::nonzero(a) returns: [[1, 4, 5, 7, 9, 15, 16, 20]].

can you tell me how to convert result of numcpp to numpy format? Thanks a lot.

**Comment by dpilger26** [comment]
For consistency I went ahead and updated the outputs of nc::nonzero() and NdArray.nonzero() to match NumPy by outputting the row and column indices instead of the flattened indices.  The flattened indices can be obtained by using nc::flatnonzero() and NdArray.flatnonzero(). 

```cpp
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>

int main()
{
    auto a = nc::NdArray<int>{
        {0, 1, 0, 0, 1, 1, 0},
        {1, 0, 1, 0, 0, 0, 0},
        {0, 1, 1, 0, 0, 0, 1} 
    };
    std::cout << "a = \n" << a;

    auto [rows, cols] = nc::nonzero(a);
    std::cout << "rows = " << rows; // [[0, 0, 0, 1, 1, 2, 2, 2]]
    std::cout << "cols = " << cols; // [[1, 4, 5, 0, 2, 1, 2, 6]]

    std::cout << "indices = " << nc::flatnonzero(a); // [[1, 4, 5, 7, 9, 15, 16, 20]]

    return EXIT_SUCCESS;
}
```
