### ISSUE TITLE
whats the differece from boost.python?

### ISSUE THREAD

**Issue by YangHR0805** [dpilger26/NumCpp#4]
https://www.boost.org/doc/libs/1_64_0/libs/python/doc/html/numpy/tutorial/ndarray.html
Example: 
```c++
#include <boost/python/numpy.hpp>
#include <iostream>

namespace p = boost::python;
namespace np = boost::python::numpy;

int main(int argc, char **argv)
{
  Py_Initialize();
  np::initialize();
}
```

**Comment by dpilger26** [comment]
Boost.python is an API for interfacing C++ with Python.  NumCpp is a full fledged library for Numpy like coding natively in C++.  I use Boost.python extensively in my test scripts to compare NumCpp functionality directly to Numpy within python.
