### ISSUE TITLE
median

### ISSUE THREAD

**Issue by angon823** [dpilger26/NumCpp#43]
I was amazingto see the description about "median": Does NOT average if array has even number of elements!
```
        // Method Description:
        ///						Return the median along a given axis. Does NOT average
        ///						if array has even number of elements!
        ///
        /// @param
        ///				inAxis (Optional, default NONE)
        /// @return
        ///				NdArray
        ///
        NdArray<dtype> median(Axis inAxis = Axis::NONE) const noexcept
```
It is not difficult to fix it, E.g. on the x axis
 ```
case Axis::ROW:
                {
                    NdArray<dtype> transposedArray = transpose();
                    NdArray<dtype> returnArray(1, transposedArray.shape_.rows);
                    for (uint32 row = 0; row < transposedArray.shape_.rows; ++row)
                    {
                        uint32 middle = (transposedArray.shape_.cols - 1) / 2;
                        stl_algorithms::nth_element(transposedArray.begin(row), transposedArray.begin(row) + middle, transposedArray.end(row));
                        if (transposedArray.shape_.cols % 2 == 0)
                        {
                            auto lhs = transposedArray(row, middle);
                            stl_algorithms::nth_element(transposedArray.begin(row), transposedArray.begin(row) + middle + 1, transposedArray.end(row));
                            auto rhs = transposedArray(row, middle + 1);
                            returnArray(0, row) = (lhs + rhs) / 2.0f;
                        }
                        else
                        {
                            returnArray(0, row) = transposedArray(row, middle);
                        }
                    }

                    return returnArray;
                }
```

I am expecting a more complete version

**Comment by dpilger26** [comment]
median() returns values of the same dtype as the input array.  Therefore if the input dtype is integral then a floating point dtype to average the two middle elements cannot be returned if the number of elements is even.  

As a compromise I have updated median() to have the same behavior as before if the input dtype is integral.  If the input dtype is floating point then the mean of the two middle elements will be output when the number of elements is even.  

e.g.
```c++
#include "NumCpp.hpp"
#include <iostream>

int main()
{
    // axis = None
    nc::NdArray<int> a = { {1, 2, 3, 4, 5, 6, 7} };
    std::cout << a.median().item() << "\n";

    nc::NdArray<int> b = { {1, 2, 3, 4, 5, 6} };
    std::cout << b.median().item() << "\n";

    auto c = b.astype<double>();
    std::cout << c.median().item() << "\n";

    // axis = ROW
    nc::NdArray<int> d = { {1, 2, 3}, {4, 5, 6}, {7, 8, 9} };
    std::cout << d.median(nc::Axis::ROW);

    nc::NdArray<int> e = { {1, 2, 3}, {4, 5, 6}, {7, 8, 9}, {10, 11, 12} };
    std::cout << e.median(nc::Axis::ROW);

    auto f = e.astype<double>();
    std::cout << f.median(nc::Axis::ROW);

    // axis = ROW
    nc::NdArray<int> g = { {1, 2, 3}, {4, 5, 6}, {7, 8, 9} };
    std::cout << g.median(nc::Axis::COL);

    nc::NdArray<int> h = { {1, 2, 3, 4}, {5, 6, 7, 8}, {9, 10, 11, 12} };
    std::cout << h.median(nc::Axis::COL);

    auto i = h.astype<double>();
    std::cout << i.median(nc::Axis::COL);

    return EXIT_SUCCESS;
}
```

output
```
4
4
3.5
[[4, 5, 6]]
[[7, 8, 9]]
[[5.5, 6.5, 7.5]]
[[2, 5, 8]]
[[3, 7, 11]]
[[2.5, 6.5, 10.5]]
```

**Comment by angon823** [comment]
> median() returns values of the same dtype as the input array. Therefore if the input dtype is integral then a floating point dtype to average the two middle elements cannot be returned if the number of elements is even.
> 
> As a compromise I have updated median() to have the same behavior as before if the input dtype is integral. If the input dtype is floating point then the mean of the two middle elements will be output when the number of elements is even.
> 
> e.g.
> 
> ```c++
> #include "NumCpp.hpp"
> #include <iostream>
> 
> int main()
> {
>     // axis = None
>     nc::NdArray<int> a = { {1, 2, 3, 4, 5, 6, 7} };
>     std::cout << a.median().item() << "\n";
> 
>     nc::NdArray<int> b = { {1, 2, 3, 4, 5, 6} };
>     std::cout << b.median().item() << "\n";
> 
>     auto c = b.astype<double>();
>     std::cout << c.median().item() << "\n";
> 
>     // axis = ROW
>     nc::NdArray<int> d = { {1, 2, 3}, {4, 5, 6}, {7, 8, 9} };
>     std::cout << d.median(nc::Axis::ROW);
> 
>     nc::NdArray<int> e = { {1, 2, 3}, {4, 5, 6}, {7, 8, 9}, {10, 11, 12} };
>     std::cout << e.median(nc::Axis::ROW);
> 
>     auto f = e.astype<double>();
>     std::cout << f.median(nc::Axis::ROW);
> 
>     // axis = ROW
>     nc::NdArray<int> g = { {1, 2, 3}, {4, 5, 6}, {7, 8, 9} };
>     std::cout << g.median(nc::Axis::COL);
> 
>     nc::NdArray<int> h = { {1, 2, 3, 4}, {5, 6, 7, 8}, {9, 10, 11, 12} };
>     std::cout << h.median(nc::Axis::COL);
> 
>     auto i = h.astype<double>();
>     std::cout << i.median(nc::Axis::COL);
> 
>     return EXIT_SUCCESS;
> }
> ```
> 
> output
> 
> ```
> 4
> 4
> 3.5
> [[4, 5, 6]]
> [[7, 8, 9]]
> [[5.5, 6.5, 7.5]]
> [[2, 5, 8]]
> [[3, 7, 11]]
> [[2.5, 6.5, 10.5]]
> ```
thank you for reply.

I think maybe it should only return double type, but not  the same dtype as the input array.? otherwise the integer type still does not meet the meaning of median.
