### ISSUE TITLE
np.outer() supported?

### ISSUE THREAD

**Issue by Kazuhito00** [dpilger26/NumCpp#45]
Hi.
Will be support outer() method?
I'm sorry if I overlooked.

**Comment by dpilger26** [comment]
I'll see about implementing it this weekend. Thanks for pointing that out.

**Comment by dpilger26** [comment]
See the [docs ](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#a395197f9b1d3f53a5fdcd234fa6e6baf) for the newly added outer() function.

**Comment by Kazuhito00** [comment]
Thank you so much!
