### ISSUE TITLE
Numpy diag in Numcpp

### ISSUE THREAD

**Issue by Houman-HM** [dpilger26/NumCpp#46]
Hey,
I was wondering if you could let me know how I can get numpy.diag in Numcpp. I could not find anything regarding that method in the documentation. There is nc:diagonal, which is different with numpy.diag. Wondering if you have already implemented numpy.diag .

Thanks in advance.

**Comment by dpilger26** [comment]
@Houman-HM
I've added a new [diag()](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#a048ad05482042e40c8044d15c4749c35) function that I believe is matching NumPy functionality.  There are three functions dealing with diagonals in NumCpp: [diag()](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#a048ad05482042e40c8044d15c4749c35), [diagflat(),](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#a38e59bc5dd8d662f1d82448cc170817d) and [diagonal()](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#ae7bb84601bd94086fe853474fa35fb64).  Once again I believe these three functions are all matching the NumPy functionality.  Thank you for pointing out this issue.

**Comment by Houman-HM** [comment]
Thanks for the quick reply!

**Comment by Houman-HM** [comment]
There is a compilation error, which the compiler cannot find diagflat.hpp header file. The header file is named as "diagFlat.hpp" but it's included as "diagflat.hpp" in the other functions.

**Comment by dpilger26** [comment]
Sorry about that.  I had updated the filename to [diagflat.hpp](https://github.com/dpilger26/NumCpp/blob/master/include/NumCpp/Functions/diagflat.hpp) to match the case of the function name inside.  Apparently Git isn't too good at picking up on case sensitive name changes... It is fixed now.

**Comment by Houman-HM** [comment]
Thanks a Zillion. 
I was wondering if it is possible for you to add numpy.linalg.solve() function to Numcpp as well.

**Comment by dpilger26** [comment]
Using ```nc::linalg::lstsq``` is the safest way to solve this type of problem.  

The NumPy documentation for numpy.linalg.solve shows this example:
```python
>>> a = np.array([[3,1], [1,2]])
>>> b = np.array([9,8])
>>> x = np.linalg.solve(a, b)
x
array([2.,  3.])
```

The NumCpp version would look like:
```cpp
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>

int main()
{
    // solves the linear equation a * x = b for x
    nc::NdArray<double> a = { { 3, 1 }, { 1, 2 } };
    nc::NdArray<double> b = { 9, 8 };
    auto x = nc::linalg::lstsq(a, b);

    std::cout << "x:\n" << x << "\n";

    return EXIT_SUCCESS;
}
```
with output:
```
x:
[[2.000000, 3.000000, ]]
```

**Comment by Houman-HM** [comment]
OK, thanks for the help.
