### ISSUE TITLE
Compilation error: ambiguous overload for operator

### ISSUE THREAD

**Issue by Houman-HM** [dpilger26/NumCpp#47]
I just installed Numcpp on a new machine and tried to compile a piece of code which was working on another machine. 
However, on the new machine, I get compilation  `error: ambiguous overload for ‘operator+’ (operand types are ‘nc::NdArray<double>’ and ‘int’). `
There are errors related to the ambiguity for nearly all the operators.
I was wondering if you could help me fix this issue.
I am using Boost 1.7, Clang 6.0, and tried different versions of gcc, including 7 , 8.3.0, 9.2.
Thanks in advance.

**Comment by dpilger26** [comment]
Can you give me some example code that is producing this error for you?

**Comment by dpilger26** [comment]
Oh, I see the issue.  It looks like you are mixing types. This error is for the operator for adding a scalar to an array. Since the array dtype is double you need to make sure your scalar input is double as well.

**Comment by Houman-HM** [comment]
Thanks for the reply.
This a sample code that prompts the same error when compiling.
` nc::NdArray <double> P = nc::power(t,8) * 10.0 + nc::power(t,7) * 720.0 * (t * 2 - 2) + nc::power(t,6) * 12.0 * nc::power((-t + 1),2);`

I do agree with what you're saying, however, the exact same piece of code compiles just fine on another computer. I am guessing that it might be related to compiler version or of that sort.

**Comment by dpilger26** [comment]
It looks like you would need to change ```(t * 2 - 2)``` to ```(t * 2.0 - 2.0)```, and ```(-t + 1)``` to ```(-t + 1.0)```.  Most likely your other compiler was doing an implicit conversion from ```int``` to ```double``` for you.  I bet if you turned up the error level you would have seen warnings from your compiler that it was doing that.  What was the other compiler you were using out of curiosity?

**Comment by Houman-HM** [comment]
Aha, I'll try to change my code. I donno about the other compiler version as it was not my own computer. 
Further on the aforementioned issue, I have also noticed the same behavior when trying do any sort of arithmetic operation with a scalar value and an nc::NdArray. In order to get the arithmetic operation working I need to put the scalar value on the right side of the nc::NdArray. For instance, if I write `2.0 * nc::NdArray<double>`, it would throw an error and as the result I should write it as `nc::NdArray <double> * 2`. I don't know why it should be like that.

**Comment by dpilger26** [comment]
No it shouldn't be like that.  You should be able to multiply a scalar and an array in either order.  This code snippet compiles and runs on clang 6.0, gcc 9.1, and Visual Studio 2019.

```cpp
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>

int main()
{
    auto a = nc::random::randInt<int>({ 5, 5 }, 0, 10);
    std::cout << "a:\n" << a << "\n";

    auto b = a + 2;
    std::cout << "b:\n" << b << "\n";

    auto c = 2 + a;
    std::cout << "c:\n" << c << "\n";
    std::cout << std::boolalpha << "a equal b " << nc::array_equal(b, c) << "\n\n";

    auto d = 2 * a;
    std::cout << "d:\n" << d << "\n";

    auto e = a * 2;
    std::cout << "e:\n" << e << "\n";
    std::cout << std::boolalpha << "d equal e " << nc::array_equal(d, e) << "\n\n";

    return EXIT_SUCCESS;
}
```

Can you give me a code snippet that isn't working for you?

**Comment by Houman-HM** [comment]
It was my bad @dpilger26. The issue got solved when I replaced the integer values with double. Now I can multiply a scalar in either order.
Thanks again.
