### ISSUE TITLE
nc::array misunderstanding / issue

### ISSUE THREAD

**Issue by SolodovRD** [dpilger26/NumCpp#52]
Thank you very much for the project.
However, here is one thing I cannot resolve so far...May be it is just my week python understanding (not familiar).
Python project, which I try to convert into C++ QT project has a line like img = numpy.array(img, dtype=numpy.uint8);

Which, in c++  should looks like nc::array(img, nc::uint8);
but it is not works..
Appreciate if you can show hot to solve.
Thanks

**Comment by vietlq** [comment]
`week python` => `weak python`

**Comment by SolodovRD** [comment]
Easy...
Here is more code for context..
def get_descriptors(img):
	clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
	img = clahe.apply(img)
	img = image_enhance.image_enhance(img)
	img = numpy.array(img, dtype=numpy.uint8)
	# Threshold
	ret, img = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)
	# Normalize to 0 and 1 range
	img[img == 255] = 1

	#Thinning
	skeleton = skeletonize(img)
	skeleton = numpy.array(skeleton, dtype=numpy.uint8)
	skeleton = removedot(skeleton)

**Comment by dpilger26** [comment]
While the goal of NumCpp is to be as close to an API match to NumPy as possible, C++ and Python are still very different languages that do not always allow for a perfect one-to-one mapping between the two libraries.  From you example I'm going to assume that ```img``` is a ```cv::Mat``` object.  So creating an ```nc::NdArray``` object from ```img``` would look something like:
```cpp
auto ncImg = nc::asarray(img.data(), img.size).astype<nc::uint8>().resize(img.rows, img.cols);
```  
or more directly just call the nc::NdArray constructor like:
```cpp
auto ncImg = nc::NdArray<nc::uint8>(img.data(), img.size).resize(img.rows, img.cols);
```
Both of the above examples make a copy of the underlying data.  You can also allow the nc::NdArray to act as a "shell" and allow the cv::Mat to keep custody of the underlying data by:
```cpp
auto ncImg = nc::NdArray<nc::uint8>(img.data(), img.rows, img.cols, false);
```
Of course you need to be careful about lifetime and scope of ```img``` with this approach.
