### ISSUE TITLE
Linspace, nonzero value

### ISSUE THREAD

**Issue by Nawrok** [dpilger26/NumCpp#55]
When I'm using linspace with double, everything works fine, but if argument have to be 0, there is for example value like this -3.60684e-14. It's very small number, but have to be a zero value.

![image](https://user-images.githubusercontent.com/58603575/76032198-a5f08780-5f39-11ea-9105-99616c9a8426.png)

**Comment by dpilger26** [comment]
Thanks for pointing this out.  It had to do with floating point "errors" accumulating as I filled the array.  I've updated linspace() to prevent this.
