### ISSUE TITLE
Library does not work with std::complex.

### ISSUE THREAD

**Issue by trcwm** [dpilger26/NumCpp#58]
First of all -- thank you for making this library! 

**Is your feature request related to a problem? Please describe.**
Numpy can work with complex numbers in the vectors. Complex numbers are common in digital signal processing. For example, determining filter frequency responses requires them.

The current NumCpp version gives me lots of '#define STATIC_ASSERT_ARITHMETIC(dtype) static_assert(std::numeric_limits<dtype>::is_specialized, "Can only be used with arithmetic types")' errors when trying to use std::complex<float> 

This error seems to be coming from the NdArray constructor.

**Describe the solution you'd like**
Extend the library to allow usage of std::complex<..>.

**Describe alternatives you've considered**
There are no alternatives besides using a different library that does support complex numbers.

**Comment by dpilger26** [comment]
Added full support for `std::complex<T>` in version 2.0.0 release.  See the documentation [here](https://dpilger26.github.io/NumCpp/doxygen/html/index.html) for more details.

**Comment by trcwm** [comment]
Thank you! :+1:
