### ISSUE TITLE
std::vector<std::vector<double>> to NdArray<double>

### ISSUE THREAD

**Issue by georgios-v** [dpilger26/NumCpp#59]
**Is your feature request related to a problem? Please describe.**
My existing algorithms produce a 2d matrix in the form of std::vector<std::vector<double>> of equal size

**Describe the solution you'd like**
there should be a constructor to a 2D NdArray with std::vector<std::vector<double>> as input. It parallels the existing initializer list constructor

**Describe alternatives you've considered**
I have not found any alternative as it seems impossible to construct what I want with the existing API. So if this functionality exists the documentation fails to explain how it is provided.

**Comment by georgios-v** [comment]
So after I posted this I found out that this seems to work:
```
std::vector<std::vector<double>> vv(n_samples, std::vector<double>(n_samples, 0.0));
auto s = nc::NdArray<double>(n_samples, n_samples);
for (int i = 0; i < n_samples; ++i) {
	s(i, s.cSlice()) = nc::fromiter<double>(vv[i].begin(), vv[i].end());
}
```
Is this the proper way to do it? Even so there should be a constructor still.

**Comment by dpilger26** [comment]
No, what you have above will not work.  Slicing operations in NumCpp return copies.  You could modify your example by using one the overloaded put() methods.  However, the most efficient way to do what you are trying to do would be to directly loop over the data. 

```cpp
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>
#include <numeric>
#include <vector>

int main()
{
    // create a vector<vector> and fill with monotonically increasing values
    const nc::uint32 n_samples = 10;
    std::vector<std::vector<double>> vv(n_samples, std::vector<double>(n_samples, 0.0));

    double start = 0.0;
    for (auto& row : vv)
    {
        std::iota(row.begin(), row.end(), start);
        start += row.size();
    }

    // convert the vector<vector> to NdArray
    auto s = nc::NdArray<double>(n_samples, n_samples);
    for (nc::uint32 row = 0; row < n_samples; ++row) 
    {
        for (nc::uint32 col = 0; col < n_samples; ++col)
        {
            s(row, col) = vv[row][col];
        }
    }

    // display the array for sanity
    std::cout << s;

    return EXIT_SUCCESS;
}
```
I'm working on a fairly large update at the moment that should be ready to release in 2 weeks or so.  I'll add additional constructors in this update to more directly accomplish what you are trying to do.

**Comment by dpilger26** [comment]
Added additional `NdArray` constructor overloads including `std::vector<std::vector<T>>` into the version 2.0.0 release.  See the documentation [here](https://dpilger26.github.io/NumCpp/doxygen/html/classnc_1_1_nd_array.html#a9d7045ecdff86bac3306a8bfd9a787eb) for more information.
