### ISSUE TITLE
not a bug, just a problem, compile with mfc failed.  with min max in DtypeInfo.hpp

### ISSUE THREAD

**Issue by aslucky** [dpilger26/NumCpp#60]
**Describe the bug**
vs2019 mfc project c++17 support
#include <NumCpp/NumCpp.hpp>

1>E:\project\cpp\fireworks\Library\include\NumCpp\NumCpp\Core\DtypeInfo.hpp(88,32): warning C4003: not enough arguments for function-like macro invocation 'min'
1>E:\project\cpp\fireworks\Library\include\NumCpp\NumCpp\Core\DtypeInfo.hpp(90,48): warning C4003: not enough arguments for function-like macro invocation 'min'
1>E:\project\cpp\fireworks\Library\include\NumCpp\NumCpp\Core\DtypeInfo.hpp(98,32): warning C4003: not enough arguments for function-like macro invocation 'max'
1>E:\project\cpp\fireworks\Library\include\NumCpp\NumCpp\Core\DtypeInfo.hpp(100,48): warning C4003: not enough arguments for function-like macro invocation 'max'
1>E:\project\cpp\fireworks\Library\include\NumCpp\NumCpp\Core\DtypeInfo.hpp(88,1): error C2059: syntax error: ')'
1>E:\project\cpp\fireworks\Library\include\NumCpp\NumCpp\Core\DtypeInfo.hpp(102): message : see reference to class template instantiation 'nc::DtypeInfo<dtype>' being compiled
1>E:\project\cpp\fireworks\Library\include\NumCpp\NumCpp\Core\DtypeInfo.hpp(88,1): error C2334: unexpected token(s) preceding ':'; skipping apparent function body
1>E:\project\cpp\fireworks\Library\include\NumCpp\NumCpp\Core\DtypeInfo.hpp(102,5): error C2143: syntax error: missing ')' before ';'
1>E:\project\cpp\fireworks\Library\include\NumCpp\NumCpp\Core\DtypeInfo.hpp(102,5): error C2059: syntax error: ')'
1>E:\project\cpp\fireworks\Library\include\NumCpp\NumCpp\Core\DtypeInfo.hpp(102,5): error C2238: unexpected token(s) preceding ';'
1>E:\project\cpp\fireworks\Library\include\NumCpp\NumCpp\Core\DtypeInfo.hpp(102,5): fatal error C1201: unable to continue after syntax error in class template definition

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

add following define works.

#ifdef max
#undef max
#endif

#ifdef min
#undef min
#endif

namespace nc
{
...

**Comment by dpilger26** [comment]
Yes, this is one of the reasons macros are evil and should be avoided.  Unfortunately in windows projects like mfc, the `windows.h` header file (or more correctly, `windef.h` that it includes) defines these `min` and `max` macros.  I'd recommend adding `NOMINMAX` to your compiler defines, or manually un-define them the way you did.
