### ISSUE TITLE
Is support numpy's non-linear square fitting on schedule?

### ISSUE THREAD

**Issue by aslucky** [dpilger26/NumCpp#61]
**Is your feature request related to a problem? Please describe.**
Want a c++ version of numpy's polyfit. actually I have tried eigen but it's too slow. maybe I use it in a wrong way, less document I can't find information about it.
numpy's implementation is concise and clear

**Comment by dpilger26** [comment]
Added static `fit()` method to the `Poly1d` class in version 2.0.0 release.  See the documentation [here](https://dpilger26.github.io/NumCpp/doxygen/html/classnc_1_1polynomial_1_1_poly1d.html#a1526585db421bbf96dfb88d99870c201) for function call signatures.
