### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by simplestory** [dpilger26/NumCpp#63]
**Describe the bug**
Hi, I used the cmake to build the project included numcpp and it throw out an error:
```
In file included from /home/pi/NumCpp/include/NumCpp.hpp:37,
                from /home/pi/raspi_src/ras_app/src/infer.cc:12:
/home/pi/NumCpp/include/NumCpp/Functions.hpp:123:10: fatal error: NumCpp/Functions/frombuffer.hpp: No such file or directory
 #include "NumCpp/Functions/frombuffer.hpp"
```
Than, I tried to change the `frombuffer.hpp` to `fromBuffer.hpp` in `Functions.hpp` because I only found the `fromBuffer.hpp` in `NumCpp/Functions` and it throw out another error:
```
In file included from /home/pi/NumCpp/include/NumCpp.hpp:37,
                 from /home/pi/raspi_src/ras_app/src/infer.cc:12:
/home/pi/NumCpp/include/NumCpp/Functions.hpp:124:10: fatal error: NumCpp/Functions/fromfile.hpp: No such file or directory
 #include "NumCpp/Functions/fromfile.hpp"
```
So I also changed the `fromfile.hpp` to `fromFile.hpp`, but I got a new error:
```
In file included from /home/pi/NumCpp/include/NumCpp/Functions.hpp:153,
                 from /home/pi/NumCpp/include/NumCpp.hpp:37,
                 from /home/pi/raspi_src/ras_app/src/infer.cc:12:
/home/pi/NumCpp/include/NumCpp/Functions/load.hpp:31:10: fatal error: NumCpp/Functions/fromfile.hpp: No such file or directory
 #include "NumCpp/Functions/fromfile.hpp"
```

**To Reproduce**
See above

**Expected behavior**
See above

**Screenshots**
None

**Additional context**
At last, I changed the file name in `NumCpp/Functions` and it worked.
(`frombuffer.hpp` to `fromBuffer.hpp`; `fromfile.hpp` to `fromFile.hpp`)

**Comment by dpilger26** [comment]
This is an annoying little "bug" that I've run into before with git where it doesn't seem to recognize case sensitive filename changes (at least on Windows where it doesn't matter, but maybe it is better in Linux).  I've fixed the issue in Github so that frombuffer.hpp and fromfile.hpp should be all lower case now.
