### ISSUE TITLE
Libtorch tensor to NumCpp array

### ISSUE THREAD

**Issue by Hiperdyne19012** [dpilger26/NumCpp#64]
Is there any way to convert Libtorch torch::Tensor to NumCpp array?

**Comment by dpilger26** [comment]
The PyTorch [documentation](https://pytorch.org/cppdocs/api/classat_1_1_tensor.html?highlight=torch%20tensor) shows that `Tensor` has this method to access its underlying data:
```cpp
template<typename T>
T *data_ptr() const
``` 
You you should be able to use that to construct an nc::NdArray<T> as either a shell or a copy using one of the constructors 16-19 from the documentation [here](https://dpilger26.github.io/NumCpp/doxygen/html/classnc_1_1_nd_array.html#ad8160a6009ce9c0c8bbb384261ce18bb).

**Comment by Hiperdyne19012** [comment]
My Libtorch tensor dimension is 1,17,30,2. Should I set the size as 1020( 1*17*30*2)?

**Comment by Hiperdyne19012** [comment]
OK, found the answer in a previous Issues post.
