### ISSUE TITLE
Can't read .hdf5 file with nc:fromfile()

### ISSUE THREAD

**Issue by jayesh0vasudeva** [dpilger26/NumCpp#66]
<img width="838" alt="Screenshot 2020-07-22 at 10 29 57 AM" src="https://user-images.githubusercontent.com/42416623/88136157-4ce27100-cc06-11ea-868b-3083eac3677a.png">

**Comment by jayesh0vasudeva** [comment]
Kindly specify how can I specify the datatype for `nc::fromfile("matedScores.hdf5")`

**Comment by dpilger26** [comment]
`nc::fromfile` is able to read basic binary files, or text data files with space, tab, or line separated values.  It is not able to read hdf5 files.  See the documentation [here](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#ae299ba41f67aeade5634e93fd8b417c9)

To specify the data type when reading in binary or text files, you need to use the template argument, i.e for a file containing 32 bit integer values:
```cpp
auto array = nc::fromfile<nc::int32>("file.bin");
```

For reading hdf5 files I would recommend the [official C++ library from HDF Group](https://support.hdfgroup.org/HDF5/doc/cpplus_RM/index.html).

**Comment by jayesh0vasudeva** [comment]
`nc::fromfile<double>("matedScores.hdf5")` solves the purpose, it requires data type.
