### ISSUE TITLE
How to convert a 2D NdArray to a C++  2D array?

### ISSUE THREAD

**Issue by Lisicong9203** [dpilger26/NumCpp#69]
How can i get this C++ array by NumCpp?
`    float rawInputData[4][4] = {{0.0f,1.0f,2.0f,3.0f},
                                {4.0f,5.0f,6.0f,7.0f},
                                {8.0f,9.0f,10.0f,11.0f},
                                {12.0f,12.0f,14.0f,15.0f}};`

In Numpy i can use np.array.tolist() , is there have a similar function in NumCpp?

**Comment by dpilger26** [comment]
No, there is no built in method of converting an `nc::Ndarray` into a 2D C array.  You do have access to the underlying data with the `data()` method, or through the various iterators.  Can I ask why you would ever want to do this?  If you do really want to do this then the below code example would work for you.
```cpp
#include "NumCpp.hpp"

#include <algorithm>
#include <cstdlib>
#include <iostream>

int main()
{
    // construct NdArray
    nc::NdArray<float> rawInputData = {{0.0f,1.0f,2.0f,3.0f}, 
                                       {4.0f,5.0f,6.0f,7.0f}, 
                                       {8.0f,9.0f,10.0f,11.0f}, 
                                       {12.0f,13.0f,14.0f,15.0f}};

    std::cout << rawInputData << '\n';

    // construct a C Array
    float rawInputDataCArray[4][4];
    std::copy(rawInputData.begin(), rawInputData.end(), &rawInputDataCArray[0][0]);

    // verify 
    for (auto row = 0u; row < 4; ++row)
    {
        for (auto col = 0u; col < 4; ++col)
        {
            std::cout << rawInputDataCArray[row][col] << ' ';
        }
        std::cout << '\n';
    }

    return EXIT_SUCCESS;
}
```
