### ISSUE TITLE
numpy compatibility/replacement

### ISSUE THREAD

**Issue by benman1** [dpilger26/NumCpp#7]
Hi
I am not sure I understand the purpose of this project. As I understand it, it's a numpy-like tool for C++ that can be used from python. I can't find any reference (without reading the code) to what I am looking for. Is the memory-layout the same as in numpy? Can you wrap (without copying) between numpy and NumCpp? Can you use NumCpp as a drop-in replacement for numpy?
BTW, are you aware of pythran's numpy implementation?
Thanks!

**Comment by dpilger26** [comment]
"As I understand it, it's a numpy-like tool for C++ that can be used from python":
The purpose of this library is NOT to be used with Python (that is what NumPy is already for!).  The purpose is to be a C++ library for easy use of a NumPy like API within C++ projects.  It does, however, provide a way to interface your code with Python using either the Boost or Pybind11 interfaces.

"I can't find any reference (without reading the code) to what I am looking for."
There are links right from Github as well as the README to the full documentation for the library here: https://dpilger26.github.io/NumCpp.

"Is the memory-layout the same as in numpy?"
I don't know what NumPy uses for a memory layout.

"Can you wrap (without copying) between numpy and NumCpp?"
Yes, using the provided Boost or Pybind11 interface.

"Can you use NumCpp as a drop-in replacement for numpy?"
The idea was to be as close to a drop-in replacement for NumPy within C++ projects.  However I never intended this to be a drop in replacement for NumPy within Python.

**Comment by benman1** [comment]
Thanks for clarifying.

If you are not familiar with the numpy memory layout, I take it the copy operation is still necessary.
