### ISSUE TITLE
Unable to change the value of an array slice.

### ISSUE THREAD

**Issue by MuyangDu** [dpilger26/NumCpp#70]
**Describe the bug**
Unable to change the value of an array slice.

**To Reproduce**
nc::NdArray<float> *mels = new nc::NdArray<float>{1,2,3,4,5};
std::cout << *mels << std::endl;
float* aaa = new float[2]{1000, 1000};
(*mels)(0, {0, 2}) = *aaa;
std::cout << (*mels)(0, {0, 2}) << std::endl;
std::cout << *mels << std::endl;

**Expected behavior**
The expected output should be 
[[1, 2, 3, 4, 5, ]]
[[1000, 1000, ]]
[[1000, 1000, 3, 4, 5, ]]

But the actual output is
[[1, 2, 3, 4, 5, ]]
[[1, 2, ]]
[[1, 2, 3, 4, 5, ]]

I'm not sure if this is a bug or I'm using NumCpp the wrong way. Thanks for your help!

**Comment by dpilger26** [comment]
There are a number of issues with your example that make it not valid C++ code (won't compile), but I'll take a stab at answering what I *think* you are asking.  First thing that you need to know is that **NumCpp** slice operations return copies rather than reference views.  So you need to use one of the various `put()` overloaded methods.  Second thing is that `nc::NdArray` already stores its internal data array on the heap so there is no need to use `new`.  Lastly, the **NumCpp** library was really designed to work using `nc::NdArray`s throughout, not necessary mixing the use of other types of containers (in this case old C-style arrays).  So with all that in mind the below code example accomplishes what I *think* you are looking for.

```cpp
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>

int main()
{
    // construct the first array
    nc::NdArray<int> mels = {1, 2, 3, 4, 5};
    std::cout << mels ;

    // construct the second array
    nc::NdArray<int> aaa = {1000, 1000};
    std::cout << aaa;

    // insert the values of the second array into the first
    mels.put(nc::Slice{0, 2}, aaa);
    std::cout << mels;

    return EXIT_SUCCESS;
}
```
with output
```bash
[[1, 2, 3, 4, 5, ]]
[[1000, 1000, ]]
[[1000, 1000, 3, 4, 5, ]]
```

**Comment by MuyangDu** [comment]
> There are a number of issues with your example that make it not valid C++ code (won't compile), but I'll take a stab at answering what I _think_ you are asking. First thing that you need to know is that **NumCpp** slice operations return copies rather than reference views. So you need to use one of the various `put()` overloaded methods. Second thing is that `nc::NdArray` already stores its internal data array on the heap so there is no need to use `new`. Lastly, the **NumCpp** library was really designed to work using `nc::NdArray`s throughout, not necessary mixing the use of other types of containers (in this case old C-style arrays). So with all that in mind the below code example accomplishes what I _think_ you are looking for.
> 
> ```c++
> #include "NumCpp.hpp"
> 
> #include <cstdlib>
> #include <iostream>
> 
> int main()
> {
>     // construct the first array
>     nc::NdArray<int> mels = {1, 2, 3, 4, 5};
>     std::cout << mels ;
> 
>     // construct the second array
>     nc::NdArray<int> aaa = {1000, 1000};
>     std::cout << aaa;
> 
>     // insert the values of the second array into the first
>     mels.put(nc::Slice{0, 2}, aaa);
>     std::cout << mels;
> 
>     return EXIT_SUCCESS;
> }
> ```
> 
> with output
> 
> ```shell
> [[1, 2, 3, 4, 5, ]]
> [[1000, 1000, ]]
> [[1000, 1000, 3, 4, 5, ]]
> ```

Thanks for the quick reply! Your code example works like a charm. But actually the code I posted above compiled 
 and ran successfully... Since you said that slice operations return copies explains why I can't change the value by directly assigning the value to slice. But I found that if I assign a scalar to the slice it can change the value.
E.g.
nc::NdArray *mels = new nc::NdArray{1,2,3,4,5};
(*mels)(0, 0) = 1000;
std::cout << *mels << std::endl;
The output is [[1000, 2, 3, 4, 5, ]], maybe that's because it's not slicing so it's returning the reference?

And you mentioned that I don't need to to use `new` because the internal data is already on heat. But here is what I encoutered.

![image](https://user-images.githubusercontent.com/56999108/89608380-98a04600-d8a7-11ea-9cd3-3244c129e9a6.png)

I want to use loadMel function to assign the loaded NdArray to the mels pointer defined in the first line in main function. Therefore, I use double pointer as the parameter in the loadMel function. But the truth is that after I called loadMel function in the main function, if I "cout << *mels", it gives me an empty NdArray.

But If I "new" an NdArray in the loadMel function and assign the loaded value to it, like this:
![image](https://user-images.githubusercontent.com/56999108/89608701-6e9b5380-d8a8-11ea-8fc1-69e022afc80a.png)
I can successfully access the data in main function with mels pointer. 

Any idea why this is happening? If, as you said, the NdArray already store data in heap internally. Why can't I access the data in the main function if I don't "new" an array.

Thanks very much for you help.

**Comment by dpilger26** [comment]
In your first example I was mainly referring to two lines.
First
```cpp
nc::NdArray *mels = new nc::NdArray{1,2,3,4,5};
```
`nc::NdArray` is missing the template type argument. Secondly, this line
```cpp
float aaa = new float[2]{1000, 1000};
```
which should be:
```cpp
float* aaa = new float[2]{1000, 1000};
```

In your second set of code snippets, I would highly encourage you to move away from using pointers the way you are.  In modern C++ that kind of pointer use is very unnecessary.  Your `loadMel()` function should just return the `nc::NdArray` directly.  Modern compilers support RVO, and regardless, `nc::NdArray` supports move semantics, so returning the `nc::NdArray` directly is the best approach.  
```cpp
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>
#include <string>

nc::NdArray<float> loadMel(const std::string& filename)
{
    std::cout << "Loading Mel file: " << filename << '\n';
    auto mels = nc::load<float>(filename);
    std::cout << mels;
    
    return mels;
}

int main()
{
    auto mels = loadMel("mel.npy");
    std::cout << mels;

    return EXIT_SUCCESS;
}
```

**Comment by MuyangDu** [comment]
Great. Thanks for you detailed explaniation! I will mark this as closed. :>
