### ISSUE TITLE
how can i convert nc::NdArray<nc::uint8> to nc::NdArray<int>

### ISSUE THREAD

**Issue by elepp** [dpilger26/NumCpp#72]
i use this to convert cv::mat to ncArray
auto oriNcArray = nc::NdArray<nc::uint8>(origin_image.data, origin_image.rows, origin_image.cols);
but i cannot use this
nc::where(oriNcArray > 130, 255, 0);
what should i do

**Comment by dpilger26** [comment]
I added additional `where()` overloads to Version 2.2.0 to match NumPy's, see the documentation [here](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#ac0af750215d0444ad9f0208620ca206b).

So to use the new `where()` as your example above, and then to convert the array from `nc::uint8` to `int` like the issue title, would look something like:

```cpp
#include "NumCpp.hpp"

#include <iostream>

constexpr nc::uint8 operator "" _uc(const unsigned long long arg) noexcept
{
    return static_cast<nc::uint8>(arg);
}

int main(int arg, char** argv)
{
        auto a = nc::random::randInt<nc::uint8>({10, 10}, 0_uc, 255_uc);
        std::cout << a << '\n';

        auto b = nc::where(a > 130_uc, 255_uc, 0_uc);
        std::cout << b << '\n';

        auto bInt = b.astype<int>();
        std::cout << bInt << '\n';

        return 0;
}
```
