### ISSUE TITLE
numpy like matmul feature

### ISSUE THREAD

**Issue by akash1301** [dpilger26/NumCpp#73]
Matrix multiplication is very easy and fast in python numpy. Especially, for dimension greater than 2. Does author plan to introduce this feature in the near future?

**Comment by dpilger26** [comment]
`matmul`, and more generally `dot()`, already exist in **NumCpp**.  See the documentation [here](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#ab39e4a1bc6bcd0f28dbd5806d5f2d0b9).
