### ISSUE TITLE
/usr/local/include/NumCpp/Polynomial/chebyshev_t.hpp:34:10: fatal error: boost/math/special_functions/chebyshev.hpp: 没有那个文件或目录

### ISSUE THREAD

**Issue by liangzhao123** [dpilger26/NumCpp#77]
**Describe the bug**

cannot run

**Comment by dpilger26** [comment]
Which version of boost are you using?

**Comment by liangzhao123** [comment]
the boost verison is 1.65.1



---原始邮件---
发件人: "David Pilger"<notifications@github.com&gt;
发送时间: 2020年8月29日(周六) 晚上9:52
收件人: "dpilger26/NumCpp"<NumCpp@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"LiangZhao"<1094036832@qq.com&gt;;
主题: Re: [dpilger26/NumCpp] /usr/local/include/NumCpp/Polynomial/chebyshev_t.hpp:34:10: fatal error: boost/math/special_functions/chebyshev.hpp: 没有那个文件或目录 (#77)




 
Which version of boost are you using?

**Comment by dpilger26** [comment]
I've tested with version 1.68 and up as listed on the README.  According to the boost release notes [here](https://beta.boost.org/users/history/version_1_67_0.html), the chebyshev routines were added in version 1.67, so you will need at least that version.

**Comment by liangzhao123** [comment]
thank you very much , i will try to update the boost.



---原始邮件---
发件人: "David Pilger"<notifications@github.com&gt;
发送时间: 2020年8月30日(周日) 上午10:36
收件人: "dpilger26/NumCpp"<NumCpp@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"LiangZhao"<1094036832@qq.com&gt;;
主题: Re: [dpilger26/NumCpp] /usr/local/include/NumCpp/Polynomial/chebyshev_t.hpp:34:10: fatal error: boost/math/special_functions/chebyshev.hpp: 没有那个文件或目录 (#77)




 
I've tested with version 1.68 and up as listed on the README.  According to the boost release notes here, the chebyshev routines were added in version 1.67, so you will need at least that version.
