### ISSUE TITLE
Histogram method for user defined bins(array)

### ISSUE THREAD

**Issue by 0tist** [dpilger26/NumCpp#78]
Sometimes the problems require you to define the size of the bins for the histogram, currently only uniformly distributed bins are supported.

I propose a method to create bins with a user-defined array for the `bins` argument with 2 for loops, which is O(n^2) solution.
Other than that, I was looking at some histogram algorithms, would love to know more about them, in case someone can share the sources for the same

**Comment by dpilger26** [comment]
Added to Release Version 2.3.1.

**Comment by 0tist** [comment]
can i start working on this?

**Comment by dpilger26** [comment]
I believe it is already done in the Version 2.3.1 Release.  See the documentation [here](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#abff7fb8fdafbdd8db4dad38cc5a2267c).
