### ISSUE TITLE
nd-array instead of 2d-array

### ISSUE THREAD

**Issue by aarora8** [dpilger26/NumCpp#8]
Hi,
I tried going through the function in (https://github.com/dpilger26/NumCpp/blob/master/src/NumCpp/Methods.hpp). To me, it seems that the methods like slicing are supported for 2d array but not for the nd-array. Is it true or can you please point me to an nd-array example.
Thanks

**Comment by dpilger26** [comment]
See the paragraph about the array container at the top of the README.

"CONTAINERS
The main data structure in NumpCpp is the NdArray. It is inherently a 2D array class, with 1D arrays being implemented as 1xN arrays. There is also a DataCube class that is provided as a convenience container for storing an array of 2D NdArrays, but it has limited usefulness past a simple container."
