### ISSUE TITLE
about nc::bitwise_not bug

### ISSUE THREAD

**Issue by yl255** [dpilger26/NumCpp#83]
**Describe the bug**
The function **nc::bitwise_not**  can not work right.

**To Reproduce**
The code like:
`auto a = nc::NdArray<bool>(2, 2);
a(0, 0) = false;
a(0, 1) = true;
a(1, 0) = false;
a(1, 1) = true;
auto b = nc::bitwise_not(a);
std::cout << a << std::endl;
std::cout << b << std::endl;
`

**Expected behavior**
It should be get the result like:
[[0, 1, ]
[0, 1, ]]
[[1,0, ]
[1, 0, ]]

but, the result is :
[[0, 1, ]
[0, 1, ]]
[[1, 1, ]
[1, 1, ]]

**Additional context**
My system is Windows7 x64, vs2017 community.

**Comment by dpilger26** [comment]
This is correct behavior in C++.  It doesn't really make any sense to do a bitwise operation on boolean values.

```cpp
#include "NumCpp.hpp"

#include <bitset>
#include <cstdlib>
#include <iostream>

int main()
{
    auto a = nc::NdArray<bool>(2, 2);
    a(0, 0) = false;
    a(0, 1) = true; 
    a(1, 0) = false; 
    a(1, 1) = true; 
    
    const auto b = nc::bitwise_not(a); 

    for (nc::uint32 i = 0; i < a.size(); ++i)
    {
        std::cout << std::bitset<8>(a[i]) << '\t';
        std::cout << std::bitset<8>(b[i]) << '\n';
    }
    std::cout << '\n';

    const bool value1 = true;
    const bool notValue1 = ~value1;
    const bool value2 = false;
    const bool notValue2 = ~value2;
    std::cout << std::bitset<8>(value1) << '\t' << std::bitset<8>(notValue1) << '\n';
    std::cout << std::bitset<8>(value2) << '\t' << std::bitset<8>(notValue2) << '\n';

    return EXIT_SUCCESS;
}
```

which outputs:

```bash
00000000        00000001
00000001        00000001
00000000        00000001
00000001        00000001

00000001        00000001
00000000        00000001
```

For boolean types you will want to use the `nc::logical_not` function as documented [here](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#ae90620999105f741609c7f279cac2907).

```cpp
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>

int main()
{
    auto a = nc::NdArray<bool>(2, 2);
    a(0, 0) = false;
    a(0, 1) = true; 
    a(1, 0) = false; 
    a(1, 1) = true; 

    const auto b = nc::logical_not(a);

    std::cout << a << '\n';
    std::cout << b << '\n';

    return EXIT_SUCCESS;
}
```

which outputs

```bash
[[0, 1, ]
[0, 1, ]]

[[1, 0, ]
[1, 0, ]]
```

**Comment by yl255** [comment]
Got it!
Thank you for your great work!
Best,
Yaliang
