### ISSUE TITLE
Make 1.4 branch

### ISSUE THREAD

**Issue by 66Ton99** [dpilger26/NumCpp#84]
Pleas add branch or release for **v1.4** hash commit **138406306c8e3822214f45a720ae9fe68464d305** at list for my need C++11!

**Comment by dpilger26** [comment]
Version 1.4 can now be found in the [releases tab](https://github.com/dpilger26/NumCpp/releases)

**Comment by dpilger26** [comment]
There never really was a version 1.4.  That commit was in the middle of some large, wide sweeping changes that ended up becoming version 2.0.  I did however go ahead and tag and release [version 1.3](https://github.com/dpilger26/NumCpp/releases/tag/Version_1.3.0) for you that *should* still support C++11.
