### ISSUE TITLE
nan_to_num

### ISSUE THREAD

**Issue by tod002** [dpilger26/NumCpp#86]
**Is your feature request related to a problem? Please describe.**
A mathematical function feature of numpy.nan_to_num,

To replace NaN with zero and infinity with large finite numbers (default behaviour) or with the numbers defined by the user using the nan, posinf and/or neginf keywords. See numpy reference: [https://numpy.org/doc/stable/reference/generated/numpy.nan_to_num.html](https://numpy.org/doc/stable/reference/generated/numpy.nan_to_num.html)

**Describe the solution you'd like**
Replace NaN values with zeros, or infinity with large numbers in 1D and 2D array (NdArray).

**Describe alternatives you've considered**
From Stackoverflow post, [https://stackoverflow.com/questions/38211955/equivalent-of-numpy-nan-to-num-in-c-c](https://stackoverflow.com/questions/38211955/equivalent-of-numpy-nan-to-num-in-c-c)
```
float nan_to_num(float num){
  if (isinf(num)){
    if (signbit(num))
      return -MAXFLOAT;
    else
      return MAXFLOAT;
  } else {
    return num;
  }
}
```
**Additional context**

**Comment by dpilger26** [comment]
Added to version 2.4.0 release.
