### ISSUE TITLE
Creating NdArray from cv::Mat having double values

### ISSUE THREAD

**Issue by nasircsms** [dpilger26/NumCpp#87]
Hi
I am trying to use NumCpp in my iOS project. 
I have a cv::Mat object with double values in it. But I am unable to create NdArray from this source. It is only allowing me to use nc::uint8 as type. 

auto ncArray = nc::NdArray<double>(textSource.data, textSource.rows, textSource.cols);

What can I do to have NdArray with double type from cv::Mat object ? Kindly provide some guidance on it.

**Comment by dpilger26** [comment]
The `data` member of the `cv::mat` class is of type `uchar*`, so since you haven't specifically specified a template type in the `nc::NdArray` constructor, `uchar` is what it is being deduced by the compiler (`nc::uint8` is the same thing as OpenCV's `uchar`).  So to keep things as double you need to explicitly specify the template type in the `nc::NdArray` constructor call:

```cpp
auto ncArray = nc::NdArray<double>(textSource.data, textSource.rows, textSource.cols);
```

**Comment by nasircsms** [comment]
@dpilger26  Apologies. I missed putting it as a `code`, so it removed `<double>` from the line.

I am actually calling this
    `auto ncArray = nc::NdArray<double>(textSource.data, textSource.rows, textSource.cols);`

But I get the error
`No matching constructor for initialization of 'nc::NdArray<double>'`

I am using latest from `master` branch.

==

> The `data` member of the `cv::mat` class is of type `uchar*`, so since you haven't explicitly specified a template type in the `nc::NdArray` constructor, `uchar` is what it is being deduced by the compiler (`nc::uint8` is the same thing as OpenCV's `uchar`). So to keep things as `double` you need to explicitly specify the template type in the `nc::NdArray` constructor call:
> 
> ```c++
> auto ncArray = nc::NdArray<double>(textSource.data, textSource.rows, textSource.cols);
> ```



==

> Hi
> I am trying to use NumCpp in my iOS project.
> I have a cv::Mat object with double values in it. But I am unable to create NdArray from this source. It is only allowing me to use nc::uint8 as type.
> 
> `auto ncArray = nc::NdArray<double>(textSource.data, textSource.rows, textSource.cols);`
> 
> What can I do to have NdArray with double type from cv::Mat object ? Kindly provide some guidance on it.

**Comment by dpilger26** [comment]
I was a little afraid of that.  Add a `reinterpret_cast` around the `cm::mat` pointer (and you don't need the explicit template parameter anymore):
```cpp
auto ncArray = nc::NdArray(reinterpret_cast<double*>(textSource.data), textSource.rows, textSource.cols);
```

**Comment by nasircsms** [comment]
@dpilger26 

This won't let me create NdArray.

error `Use of class template 'NdArray' requires template arguments`


> I was a little afraid of that. Add a `reinterpret_cast` around the `cm::mat` pointer (and you shouldn't need the explicit template parameter anymore):
> 
> ```c++
> auto ncArray = nc::NdArray(reinterpret_cast<double*>(textSource.data), textSource.rows, textSource.cols);
> ```

**Comment by nasircsms** [comment]
`auto ncArray = nc::NdArray<double>(reinterpret_cast<double*>(textSource.data), textSource.rows, textSource.cols);`
this compiled successfully.

Thanks a lot for your time.
I'll mention if faced any further issue with it. Otherwise I'll close it.

> @dpilger26
> 
> This won't let me create NdArray.
> 
> error `Use of class template 'NdArray' requires template arguments`
> 
> > I was a little afraid of that. Add a `reinterpret_cast` around the `cm::mat` pointer (and you shouldn't need the explicit template parameter anymore):
> > ```c++
> > auto ncArray = nc::NdArray(reinterpret_cast<double*>(textSource.data), textSource.rows, textSource.cols);
> > ```
