### ISSUE TITLE
NdArrayCore.hpp Visual Studio error

### ISSUE THREAD

**Issue by TomAvrech** [dpilger26/NumCpp#89]
In
https://github.com/dpilger26/NumCpp/blob/master/include/NumCpp/NdArray/NdArrayCore.hpp
Line 4690, You've commented:
    // NOTE: this needs to be defined outside of the class to get rid of a compiler
    // error in Visual Studio

But I see it's already outside of the class, yet I get a Visual Studio compilation error:

Severity	Code	Description	Project	File	Line	Suppression State
Error(active)	E0135	class template "nc::NdArray<dtype, Allocator>" has no member "nonzero"	my_lib	C : \NumCpp - master\include\NumCpp\NdArray\NdArrayCore.hpp	4693

What is needed to be done in order to fix this error ?

**Comment by dpilger26** [comment]
What version of Visual Studio are you using?  I've compiled and run the following example code using the `nonzero()` method of `NdArray` with VS2017 & VS2019, both Debug & Release, x86 & x64, C++14 & C++17 & C++Latest, and cannot reproduce your error.

```cpp
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>

int main()
{
    auto a = nc::random::randInt<int>({ 5, 5 }, 0, 2);
    auto indices = a.nonzero();

    std::cout << "rowIdx: " << indices.first;
    std::cout << "colIdx: " << indices.second;

    return EXIT_SUCCESS;
}

```

**Comment by TomAvrech** [comment]
> 
> 
> What version of Visual Studio are you using? I've compiled and run the following example code using the `nonzero()` method of `NdArray` with VS2017 & VS2019, both Debug & Release, x86 & x64, C++14 & C++17 & C++Latest, and cannot reproduce your error.
> 
> ```c++
> #include "NumCpp.hpp"
> 
> #include <cstdlib>
> #include <iostream>
> 
> int main()
> {
>     auto a = nc::random::randInt<int>({ 5, 5 }, 0, 2);
>     auto indices = a.nonzero();
> 
>     std::cout << "rowIdx: " << indices.first;
>     std::cout << "colIdx: " << indices.second;
> 
>     return EXIT_SUCCESS;
> }
> ```

VS2019, Release, x64, and C++17.

Notice that the code I'm using works fine with CLion. (The problem is only with Visual Studio)

**Comment by dpilger26** [comment]
Can you provide me some sample code that demonstrates the error?

Which compiler are you using with CLion? I'm assuming gcc or clang?

**Comment by TomAvrech** [comment]
> 
> 
> Can you provide me some sample code that demonstrates the error?
> 
> Which compiler are you using with CLion? I'm assuming gcc or clang?

In CLion, WinGW is used.

I'm creating a shared library (Windows DLL), and the minimal code that causes this is:
#include "pch.h"
#include "C:/NumCpp-master/include/NumCpp/Linalg/lstsq.hpp"

<img width="896" alt="Screenshot 2021-01-04 095120" src="https://user-images.githubusercontent.com/19329110/103513039-7ae50600-4e72-11eb-8b29-5cc66e80e3ee.png">

**Comment by dpilger26** [comment]
Are you properly including the boost includes? The first error is about not finding a boost file.

If you don't include pch.h is there still a problem?

MinGW is an environment. Within that environment you are probably using either the gcc or clang compiler.  That would explain why you don't see an issue when using CLion.

**Comment by TomAvrech** [comment]
The boost issue is gone (Restarted VS solved).

I must include pch.h , since this is a library project. If I remove it, I get an error, and a recommendation to include pch.h .

Current status:
<img width="868" alt="Screenshot 2021-01-04 102843" src="https://user-images.githubusercontent.com/19329110/103515755-fb5a3580-4e77-11eb-9042-e019d88677be.png">

I'm not familiar with compilers. Are you saying it's possible to use what CLion uses in Visual Studio ?

**Comment by dpilger26** [comment]
`pch.h` is Visual Studio's way of handling pre-compiled headers.  See [here](https://en.wikipedia.org/wiki/Precompiled_header) for more info.  It is never required for any type of project (library or executable).  If you go into your project settings -> Configuration Properties -> C/C++ -> Precompiled Headers -> Precompiled Header -> and toggle it to "Not Using Precompiled Headers"  it will get rid of the error and recommendation to include `pch.h`.   Try that and remove `#include "pch.h"` and let me know if you still have errors.

As for your other question, Visual Studio contains its own tool chain (precompiler, compiler, and linker).  CLion is just an IDE and requires you to tell it about an installed tool chain for it to use.  In your case you pointed it to your MinGW environment and are probably using the GNU toolchain (gcc, g++, ld).  I believe that you can point CLion to use the Visual Studio tool chain if you wanted. See [here ](https://www.jetbrains.com/help/clion/quick-tutorial-on-configuring-clion-on-windows.html#msvc-compiler) for how to do that.

**Comment by TomAvrech** [comment]
> 
> 
> `pch.h` is Visual Studio's way of handling pre-compiled headers. See [here](https://en.wikipedia.org/wiki/Precompiled_header) for more info. It is never required for any type of project (library or executable). If you go into your project settings -> Configuration Properties -> C/C++ -> Precompiled Headers -> Precompiled Header -> and toggle it to "Not Using Precompiled Headers" it will get rid of the error and recommendation to include `pch.h`. Try that and remove `#include "pch.h"` and let me know if you still have errors.
> 
> Also note that `pch.h` is only for Visual Studio. Whatever you were building successfully in CLion with MinGW gcc must not have contained that include?
> 
> As for your other question, Visual Studio contains its own tool chain (precompiler, compiler, and linker). CLion is just an IDE and requires you to tell it about an installed tool chain for it to use. In your case you pointed it to your MinGW environment and are probably using the GNU toolchain (gcc, g++, ld). I believe that you can point CLion to use the Visual Studio tool chain if you wanted. See [here ](https://www.jetbrains.com/help/clion/quick-tutorial-on-configuring-clion-on-windows.html#msvc-compiler) for how to do that.

This seems to work !
Yes, VS added pch.h. Didn't exist in CLion.
Thanks for the info about the compilers, and thanks for helping solve this :)
