### ISSUE TITLE
opeeration between nc::NdArray with scalars

### ISSUE THREAD

**Issue by vra** [dpilger26/NumCpp#90]
**Is your feature request related to a problem? Please describe.**
operatotion between nc::NdArray and scalars, e.g.,
```cpp
nc::NdArray<float> foo = nc::random::rand<float>(3, 3);
nc::NdArray<float> bar = foo + 1.0;
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dpilger26** [comment]
This already exists.  However, it is on the user to assure the correct types are being used.  In your example you are trying to add a `double` to a `float` array so this will not compile.  Make sure to add a `float` to your array and everything works:

```cpp
nc::NdArray<float> foo = nc::random::rand<float>({ 3, 3 });
nc::NdArray<float> bar = foo + 1.0f;
nc::NdArray<float> baz = 1.0f + foo;
```

**Comment by vra** [comment]
Thanks for explanation. that's exactly what I need.
