### ISSUE TITLE
multiple definition of `nc::endian::isLittleEndian()'

### ISSUE THREAD

**Issue by Tasfa** [dpilger26/NumCpp#91]
Build command failed.
src/pagedewarp/libpagedewarp.a(contours_process.cpp.o): In function `std::__ndk1::ostreambuf_iterator<char, std::__ndk1::char_traits<char> >::failed() const':
Library/Android/sdk/ndk/19.2.5345600/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/__tree:347: multiple definition of `nc::endian::isLittleEndian()'

src/pagedewarp/libpagedewarp.a(page_dewarp.cpp.o):Library/Android/sdk/ndk/19.2.5345600/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/ostream:451: first defined here

src/pagedewarp/libpagedewarp.a(build_map.cpp.o): In function `std::__ndk1::ostreambuf_iterator<char, std::__ndk1::char_traits<char> >::failed() const':
/../../../../../../third_party/numcpp/include/NumCpp/Core/Internal/Error.hpp:56: multiple definition of `nc::endian::isLittleEndian()'

src/pagedewarp/libpagedewarp.a(page_dewarp.cpp.o):Library/Android/sdk/ndk/19.2.5345600/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/ostream:451: first defined here

clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by dpilger26** [comment]
Fixed in Version 2.4.1 bug fix release.

**Comment by krithicappyhigh** [comment]
hi @Tasfa, i'm trying to build Numcpp for android but stuck in getting the boost includes working. can you tell me how you managed to build Numcpp for android? if you don't mind.
