### ISSUE TITLE
QUESTION: Can I load saved NumCpp file with the function numpy.load(...) in Python?

### ISSUE THREAD

**Issue by zerowing-ex** [dpilger26/NumCpp#92]
Your project is very useful!
In my recent project, I want to load saved NumCpp file (nc::NdArray) by using python library numpy function such as numpy.load(...), but I cannot check if the program read properly because my data is **very large** (the full shape is about (140000, 16, 100, 150, 1)).
Therefore, I'll appreciate it very much if you could help me!

**Comment by dpilger26** [comment]
`NumCpp` `dump()` and `tofile()` methods will write the `nc::NdArray` out to a binary or text tile.  That file can then be read back into Python with `NumPy` using the `np.fromfile()` method.

eg
```cpp
#include "NumCpp.hpp"

#include <cstdlib>
#include <iostream>

int main()
{
	// Make a flattened array of shape [5, 4, 3, 2, 1]
	constexpr nc::uint32 size = 5 * 4 * 3 * 2 * 1;

	// fill it with incramenting values
	auto a = nc::arange(size); 

	// write out to a binary file
	nc::tofile(a, "Test.bin");

	return EXIT_SUCCESS;
}
```

then from Python
```python
import numpy as np

a = np.fromfile('Test.bin', dtype=np.uint32).reshape(5, 4, 3, 2, 1)
```

**Comment by zerowing-ex** [comment]
Thank you for taking the time to answer my question! I'll try it layer.
