### ISSUE TITLE
How to add newaxis

### ISSUE THREAD

**Issue by Houman-HM** [dpilger26/NumCpp#94]
Dear David Pilger,

I was wondering if you could let me know if it is possible to achieve numpy.newaxis in NumCpp?
More specifically, I want to achieve the following using NumCpp:

`result = a* b [:,np.newaxis]`
 where a is a [3, 100] array and b is a 1D array of size 3.
Furthermore, is it possible to define 1D arrays using NumCpp?

Thanks.

**Comment by dpilger26** [comment]
A 1D array is just a `1xN` array in `NumCpp`.

You can achieve the equivalent of the `numpy.newaxis` functionality by using the `reshape` method (same as `Numpy`) :
```cpp
b.reshape(-1, 1);
```
The `-1` in the first argument says infer the size of the dimension based off of the size of the second input, so in this case your `1x3` array will be reshaped into `3x1`.

Unfortunately however, `NumCpp` does not currently support all of the different broadcasting rules that `NumPy` does so your example of muliplying a `3x100` and a `3x1` array will not work.  You'd have to do something a bit more manual such as:
```cpp
#include "NumCpp.hpp"

#include <algorithm>
#include <functional>
#include <iostream>

int main()
{
    const auto a = nc::ones<int>(3, 100);
    const nc::NdArray<int> b = {2, 3, 4};

    std::cout << a << '\n';
    std::cout << b << '\n';

    auto result = nc::empty_like(a);
    for (int row  = 0; row < a.numRows(); ++row)
    {
        const auto bValue = b[row];
        std::transform(a.begin(row), a.end(row), result.begin(row),
            [bValue](auto aValue) noexcept
            {
                return bValue * aValue;
            });
    }

    std::cout << result;

    return 0;
}

```

**Comment by dpilger26** [comment]
This is the same type of broadcasting from your first question and is not currently supported, so you'll have to resort to more manual methods once again. eg
```cpp
#include "NumCpp.hpp"

#include <algorithm>
#include <functional>
#include <iostream>

int main()
{
    nc::NdArray<int> a = {1, 2, 3};
    a.reshape(-1, 1) // 3x1 row vec
    const nc::NdArray<int> b = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}; // 3x3 array

    std::cout << a << '\n';
    std::cout << b << '\n';

    auto result = nc::empty_like(b);
    for (int row  = 0; row < b.numRows(); row++)
    {
        const auto aValue = a[row];
        std::transform(b.begin(row), b.end(row), result.begin(row),
            [aValue](auto bValue) noexcept
            {
                return bValue - aValue;
            });
    }

    std::cout << result;

    return 0;
}
```

which outputs:
```console
[[1, ]
[2, ]
[3, ]]

[[1, 2, 3, ]
[4, 5, 6, ]
[7, 8, 9, ]]

[[0, -1, -2, ]
[-2, -3, -4, ]
[-4, -5, -6, ]]
```

**Comment by Houman-HM** [comment]
Thanks a zillion David.
This makes it clear.
