### ISSUE TITLE
Strange results with nc::norm

### ISSUE THREAD

**Issue by ArMouReR** [dpilger26/NumCpp#97]
Hi, I am kind of new to all this stuff, so sorry for dumb questions...

I am trying to translate image processing algo from python to C++
So, I came across this library I got stuck with some basics:
I am trying to run nc::norm on 2d array on one of the axises (row, cols) and it looks like the results is missing sqrt at the end.
I see sqrt in the code, but I don't see the test of this function in the test folder.

Is it possible that nc::norm produce slightly different result then in Python ?

**Comment by dpilger26** [comment]
The unit test for norm can be found starting on line 4838 of test_funtions.py, where it is compared against np.linalg.norm.  Can you post an example where you believe your output is incorrect?

**Comment by ArMouReR** [comment]
Sorry, my bad.
The data for nc::norm came from nc::diff() and for nc::diff() I have used Mat file with image(unsigned char).
So, it was typical data types conversation problem: result of diff was unsigned and all negative values were treated as 255,254...
As soon as added .astype<nc::int16> on input of diff everything started to look as expected.
Thanks a lot for response and sorry for dumb question !!!
